TYPO3/testing-framework

Classes/Core/Acceptance/AcceptanceCoreEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php, Resources/Core/Build/FunctionalTests.xml, Resources/Core/Build/UnitTests.xml, Resources/Core/Build/UnitTestsBootstrap.php, composer.json
To finally remove the testing framework from the core and make it usable from the outside, the path handling got a slight rework.
By setting the ENV var TYPO3_PATH_PACKAGES you can define, where your vendor/ directory is. Fixtures can be loaded relative to that path, which is available as constant TYPO3_PATH_PACKAGES.
=> [TASK] Stream-Line Path Usages in Testing Framework

Classes/Core/Testbase.php
In extraction of the framework, the changes made to
testbase made here: https://review.typo3.org/#/c/51331/
got lost somehow.
Integrate these changes again.
=> [BUGFIX] Use TYPO3_PATH_ROOT instead of TYPO3_PATH_WEB

Classes/Core/Testbase.php
Since the packae is always installed in the vendor dir,
wen can remove the need to define an env var here
by just using a relative path from the testbase class
=> [TASK] Remove the need for TYPO3_PATH_PACKAGES env

Resources/Core/Build/UnitTests.xml
Sets sysext/*/Classes/ on the whitelist to be reporteded by code coverage.
This doesn't activate code coverage itself. To execute it use the code coverage
button of PphStorm or one of the --coverage-** commandline options, for
example:
--coverage-html <dir>
=> [FEATURE] Add whitelist to enable code coverage

Classes/Fluid/Unit/ViewHelpers/ViewHelperBaseTestcase.php
Allows the testing framework to correctly test VH classes which
subclass non-CMS VH classes, and allows testing VH classes
after applying https://review.typo3.org/#/c/52796/.
=> [TASK] Check method_exists before injecting ReflectionService

Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/DataHandling/DataSet.php, Classes/Core/Functional/FunctionalTestCase.php, Migrations/Code/ClassAliasMap.php
The classes in ext:core/Test/Functional/DataHandling/Framework
are pretty useful for DataHandler tests. So it comes in handy
to have them available in testing-framework instead as part of
sysext:core.
=> [TASK] Extract DataHandling Framework from ext:core

Classes/Core/Functional/FunctionalTestCase.php
The UriBuilder will fail if backend routes are not loaded.
=> [FEATURE] Initialize BackendRouter for FunctionalTests

Classes/Core/Testbase.php
The constant LF might not be defined in functional and unit test
bootstrap by the time the script terminates with an error message.
Replacing the usage of this constant with the native value for a
linebreak causes the same result for the error message, but prevents
the additional and confusing messages about the not existing constant.
=> [BUGFIX] Remove possibly undefined constant from test bootstraps

Classes/Core/Functional/FunctionalTestCase.php
The method is used in at last 4 test cases now in the core, so it makes sense to extract it.
=> Add method for modifying template record to FunctionalTestCase

Classes/Core/Functional/Framework/Constraint/RequestSection/StructureHasRecordConstraint.php
Now when asserting like:
```
$this->assertThat($responseSections, $this->getRequestSectionStructureHasRecordConstraint()
->setRecordIdentifier(self::TABLE_Content . ':' . $ttContentUid)->setRecordField('image')
->setTable('sys_file_reference')->setField('title')->setValues(...$visibleFileTitles));
``` 
A more verbose error is shown:
```
Failed asserting that structure has record.
* Section "Extbase:list()": Could not assert all values for "tt_content:299.image.sys_file_reference.title"
```
Before it was:
```
Failed asserting that structure has record.
* Section "Extbase:list()": 
```
=> Add failure message when StructureHasRecordConstraint fails

Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
$pathsToLinkInTestInstance already allows to create symbolic links from
outside into the testing instance. However, in case these resource shall
be modified inside the testing instance, having real stand-alone
resources is better.
$pathsToProvideInTestInstance is introduced which behaves similar to
$pathsToLinkInTestInstance with the important difference that resources
are duplicated now instead of being linked.
Resolves: #42
=> [FEATURE] Add possibility to duplicate paths instead of creating links

Classes/Core/Testbase.php
Since TYPO3 will throw exceptions when extension
configuration is not present and added tests extensions
can bring their own configuration, we need to ensure
that configuration for all active extensions is present
before including their ext_localconf.php files.
=> [BUGFIX] Create extension configuration on boot

Classes/Core/Acceptance/AcceptanceCoreEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Unit/UnitTestCase.php, Resources/Core/Build/UnitTestsBootstrap.php, composer.json
Major version raise bringing core v9-only compatibility
and a UnitTestCase base class that no longer supresses
E_NOTICE PHP level errors by default.
=> Preparing v3.0.0

Classes/Core/Acceptance/AcceptanceInstallMysqlCoreEnvironment.php, Classes/Core/Acceptance/AcceptanceInstallPgsqlCoreEnvironment.php
After installation tests start from a clean slate, each test
must take care of cleaning up all leftovers from former test runs.
=> [TASK] Cleanup test environment for each installation test

Classes/Core/Testbase.php, composer.json
The change introduced in 75593767e3f1127ec9800f0f6dc0d1bd56c6e516
is no longer required as https://review.typo3.org/55434 improved the
extension configuration API in TYPO3 v9.1.
That patch introduced ondemand ext_conf_template.txt parsing to create
an entry in the LocalConfiguration.php EXTENSIONS setting storage
(when not available) during a call to ExtensionConfiguration::get().
=> [TASK] Do not synchronize extension configuration templates in Testbase

Resources/Core/Build/Configuration/Acceptance/Support/Helper/Acceptance.php
Checks for browser console errors after every acceptance tests step,
and fails when there are any.
=> Fail when there are errors in the browser console

Resources/Core/Build/Configuration/Acceptance/Support/Helper/Acceptance.php
Before, first error message was skipped.
=> [BUGFIX] Print first console error message on test failure

Classes/Core/BaseTestCase.php, Classes/Core/Unit/UnitTestCase.php
The Environment object is immutable for any TYPO3 instance, but
tests can initialize their own. In oder to keep tests side
effect free, after each of such tests the original Environment
has to be restored.
New functions to backup and restore this object ready to be used
in Test classes provide an easy solution to that task.
=> [FEATURE] Backup and Restore Environment Object in Tests

Classes/Core/Acceptance/AcceptanceCoreEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php
The patch https://review.typo3.org/c/56017/ is about to remove EXT:lang. This must be reflected in the testing framework.
=> [TASK] Remove EXT:lang as core extension to load

Resources/Core/Build/Configuration/Acceptance/Support/AcceptanceTester.php
Before switching to a new frame, make sure
the performed action has been finished. In
Backend, the nprogress bar status can be used
for that.
=> [TASK] Safeguard switchToIFrame function

Classes/Core/Acceptance/AcceptanceCoreEnvironment.php, Classes/Core/Acceptance/AcceptanceInstallMysqlCoreEnvironment.php, Classes/Core/Acceptance/AcceptanceInstallPgsqlCoreEnvironment.php
The environment variable TYPO3_PATH_ROOT must be set to the
test folder generated by the bootstrap. This is already the
case for functional tests but not for the acceptance tests.
If the environment variable is not set, the configuration files
like PackageStates.php is not loaded from the test folder but
from the root folder.
=> [BUGFIX] Set correct TYPO3 root path in acceptance tests

Classes/Core/FileStreamWrapper.php
Just for reference. Drupal has the same check in their DrupalLocalStreamWrapper (https://api.drupal.org/api/drupal/includes%21stream_wrappers.inc/function/DrupalLocalStreamWrapper%3A%3Astream_metadata/7.x)
=> [BUGFIX] Prevent notice on empty touch arguments

Resources/Core/Build/Scripts/splitFunctionalTests.php, Resources/Core/Build/Scripts/splitFunctionalTests.sh
splitFunctionalTests.sh creates single phpunit xml configuration
files to split the huge set of functional tests into pieces.
The script is rewritten as splitFunctionalTests.php, now understands
and correctly counts @dataProvider annotations and distributes the
functionals more equally.
=> [TASK] New script to split functional tests

Classes/Core/Testbase.php
- To get correct paths change cwd
- Resolve from path to absolute path before creation
=> [BUGFIX] Fix symlink creation on windows

Resources/Core/Build/Configuration/Acceptance/Support/AcceptanceTester.php
Almost all Cests include the fully loaded routine
right after the useExistingSession call. In order
to ease the setup for new Cests, include the routine
into useExistingSession
=> [TASK] Simplify useExistingSession setup

Classes/Core/Acceptance/Extension/BackendCoreEnvironment.php, Classes/Core/Functional/Framework/AssignablePropertyTrait.php, Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/DataHandling/Scenario/DataMapFactory.php, Classes/Core/Functional/Framework/DataHandling/Scenario/EntityConfiguration.php, Classes/Core/Functional/Framework/Frontend/Hook/BackendUserHandler.php, Classes/Core/Functional/Framework/Frontend/Hook/FrontendUserHandler.php, Classes/Core/Functional/Framework/Frontend/InternalRequest.php, Classes/Core/Functional/Framework/Frontend/InternalRequestContext.php, Classes/Core/Functional/Framework/Frontend/InternalResponse.php, Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php, Classes/Core/Functional/Framework/Frontend/Response.php, Classes/Core/Functional/Framework/Frontend/ResponseContent.php, Classes/Core/Functional/Framework/Frontend/ResponseSection.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php, Resources/Core/Functional/Extensions/json_response/Classes/Encoder.php, Resources/Core/Functional/Extensions/json_response/Configuration/RequestMiddlewares.php, Resources/Core/Functional/Extensions/json_response/ext_emconf.php, Resources/Core/Functional/Fixtures/Frontend/request.tpl
Basically this change introduces the possibility to make use of (pseudo) PRS-7 request/response handling in frontend functional testing as well. Besides that, whole database scenarios can be declared using a new data declaration written in YAML.
=> [FEATURE] Enhance functional test frontend and scenario handling

Classes/Core/DatabaseConnectionWrapper.php, Classes/Core/Functional/FunctionalTestCase.php
In SQL Server (MSSQL), hard setting uid auto-increment primary keys is
only allowed if the table is prepared for such an operation beforehand.
When executing functional test cases a new database connection wrapper
is invoked, which automatically modifies IDENTITY_INSERT in case the
use database platform is SQL Server.
=> [BUGFIX] Modify SQL Server IDENTITY_INSERT when creating records

Classes/Core/Functional/Framework/Frontend/InternalResponseException.php, Classes/Core/Functional/FunctionalTestCase.php
e.g. Doctrine\DBAL\Exception\DriverException cannot be reconstituted
with just message and code, but requires additional context.
=> [BUGFIX] Fallback to internal exception in case it cannot be created

Classes/Core/DatabaseConnectionWrapper.php
the condition before looks like a typo, and it throws a notice 
PHP Notice: Undefined index: cf_extbase_datamapfactory_datamap in TYPO3/7/vendor/typo3/testing-framework/Classes/Core/DatabaseConnectionWrapper.php on line 77
=> fix empty condition in DatabaseConnectionWrapper->shallModifyIdentityInsert

Classes/Core/Testbase.php
This fixes notices like "Constant ... already defined"
=> Check if constants are defined before defining them

Classes/Core/Testbase.php
This is not necessary anymore with the proper closing of
existing database connections by https://review.typo3.org/58189
=> [TASK] Drop connection reset

Classes/Core/Testbase.php
Using the subtree packages of TYPO3, the typo3 folder isn't a symlink
anymore. Thus the realpath cannot be used to resolve the path to
autoload. As the testing framework requires composer mode, the path
can simply be resolved from the current directory.
=> [BUGFIX] Use correct path to autoload.php

Classes/Core/Acceptance/Extension/BackendCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallMysqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallPostgresqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallSqliteCoreEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php
To simplify functional and acceptance testing within extensions,
the bootstrap now adds environment var TYPO3_PATH_APP to the same
path as TYPO3_PATH_ROOT - both lead to the "instance" path in
typo3temp/var/tests. Core bootstrap will then for pick
"instancePath"/typo3temp/var for caches and other stuff which
may otherwise be located outside of the instance in composer
based installations.
=> [TASK] putenv TYPO3_PATH_APP in functional and acceptance setup

composer.json
Master now requires "10.*.*@dev" for core package dependencies,
effectively making branch 9 the core v9 compat branch.
=> [TASK] Prepare master branch for core v10

Classes/Core/Functional/FunctionalTestCase.php
If a frontend request fails, the content of stderr is now rendered to
get the reason why a request failed. Previously, in such cases the
tests simply stated that there is no content at all.
=> [TASK] Render error message of failed frontend requests

Classes/Core/DatabaseConnectionWrapper.php
This commit doesn't exclude tables without TCA anymore for data insertion.
This fixes an issue with mssql where inserting values into an identity
column fails due to missing TCA.
Resolves: #127
=> [BUGFIX] Include all tables for data insertion

Classes/Core/Functional/FunctionalTestCase.php
The command defined in `initCommands` only works with MySQL and MariaDB,
thus this setting must not be set on any other DBMS.
=> [BUGFIX] Only set initCommands on MySQL

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php
due to the core change, tables now start with `cache_*` for the database.
=> [BUGFIX] Never snapshot cf_* or cache_* tables

Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Unit/UnitTestCase.php, Classes/Fluid/Unit/ViewHelpers/ViewHelperBaseTestcase.php, composer.json
This reverts commits b130f30d57eec75683d90ec43e2e4b54c6c4c98c and
2cc4d197426e80fdde66a579b02ceca3f4fa2b16.
This caused a breaking change for not prepared users.
=> Revert "Update phpunit to version 8"

Classes/Core/Functional/Framework/DataHandling/CsvWriterStreamFilter.php, Classes/Core/Functional/Framework/DataHandling/DataSet.php
Albeit enclosing values is only required for according literals
(spaces, new-lines, tabs) it should be ensured that re-exporting
data-sets does not modify too much in existing CSV assertion files.
=> [TASK] Enforce DataSet CSV export enclosure

Classes/Core/Testbase.php, Resources/Core/Build/UnitTestsBootstrap.php, composer.json
In order to run testing-framework v5 (= master) with v9 and master (v10) of TYPO3 Core,
some functionality was re-added.
A main switch within testbase was added to still allow to use PATH_site et al.
=> [FEATURE] Make testing framework compatible with TYPO3 v9 Core and master

Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php
Frontend User Authenticaiton should be bound
to the PSR-7 request object, not to TSFE,
as this is done at a later stage now.
This has to be merged with 
https://review.typo3.org/c/Packages/TYPO3.CMS/+/61155
=> [BUGFIX] Move middleware logic away from TSFE

Resources/Core/Build/Scripts/splitAcceptanceTests.php
To speed up execution of acceptance tests in bamboo, the available
test files are split into work packages. The script only considers
test files located in typo3/sysext/core/Acceptance/Backend.
With the new main folder InstallTool, that contains tests concerning
the stand alone install tool, the script must also consider those
files for work packages.
=> [TASK] Add new Acceptance Tests folder to splitter script

Classes/Core/BaseTestCase.php, Classes/Core/Functional/Framework/AssignablePropertyTrait.php, Classes/Core/Functional/Framework/Constraint/RequestSection/AbstractRecordConstraint.php, Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/DataHandling/DataSet.php, Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php, Classes/Core/Functional/Framework/DataHandling/Scenario/EntityConfiguration.php, Classes/Core/Functional/Framework/Frontend/Collector.php, Classes/Core/Functional/Framework/Frontend/Hook/TypoScriptInstructionModifier.php, Classes/Core/Functional/Framework/Frontend/Internal/ArrayValueInstruction.php, Classes/Core/Functional/Framework/Frontend/Internal/TypoScriptInstruction.php, Classes/Core/Functional/Framework/Frontend/InternalRequest.php, Classes/Core/Functional/Framework/Frontend/InternalRequestContext.php, Classes/Core/Functional/Framework/Frontend/InternalResponse.php, Classes/Core/Functional/Framework/Frontend/Parser.php, Classes/Core/Functional/Framework/Frontend/Renderer.php, Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php, Classes/Core/Functional/Framework/Frontend/Response.php, Classes/Core/Functional/Framework/Frontend/ResponseContent.php, Classes/Core/Functional/Framework/Frontend/ResponseSection.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php, Classes/Core/Unit/UnitTestCase.php, Classes/Fluid/Unit/ViewHelpers/ViewHelperBaseTestcase.php, Resources/Core/Build/UnitTests.xml, Resources/Core/Build/UnitTestsDeprecated.xml
- Use FQDN for use statements
- Fix some variable names and phpdoc info (typos mostly)
- Remove unused functionality
- Simplify code (e.g. notices via PHPunit directly)
- Use native PHP functionality over Core APIs when useful
=> [TASK] Clean up code base

Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseSnapshot.php
Functional tests can be streamlined, in order
to rely less on a specific TYPO3 version.
=> [TASK] Remove unnecessary dependencies to TYPO3

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Acceptance/Extension/InstallMysqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallPostgresqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallSqliteCoreEnvironment.php, Classes/Core/BaseTestCase.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php, Resources/Core/Build/FunctionalTests.xml, Resources/Core/Build/FunctionalTestsBootstrap.php, Resources/Core/Build/UnitTests.xml, Resources/Core/Build/UnitTestsBootstrap.php, Resources/Core/Build/UnitTestsDeprecated.xml
phpunit has advanced since 2012, so we can
get rid of lots of functionality that TYPO3 built
on its own by using phpunit-built-in functionality:
* Use the .xml specs to define constants, env variables and init settings
* No need to set $backupGlobals=true as this is set by .xml spec
* Do not rely on workarounds for old core versions (like trustedHostsPattern settings)
This makes especially the BaseTestCase and the UnitTests Bootstrap
less complicated.
=> [TASK] Use PHPunit specs instead of custom Testbase code

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Acceptance/Extension/InstallMysqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallPostgresqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallSqliteCoreEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
Functionals need to have each TYPO3_CONTEXT=Testing
applied as they also execute Frontend Requests
where the context might be modified.
=> [BUGFIX] Re-add TYPO3_CONTEXT assignment

Classes/Core/BaseTestCase.php
The two helper functions in the "BaseTestCase" should
either be built manually by using the accessible mock
or by using closures to change the scope of the method.
=> [!!!][TASK] Drop support for "callInaccessibleMethod" and "inject"

composer.json
PHPUnit 8.4 is incompatible to 8.3 since some error classes were moved
into a different namespace.
=> [BUGFIX] Require phpunit/phpunit with minimal of 8.4

Classes/Core/Testbase.php
If the instance to test is a composer-based installation, the vendor
folder is usually not situated in the docroot, but one level above.
Add a second check for this case.
=> [TASK] Make functional tests composer compatible

Classes/Core/Acceptance/Extension/InstallPostgresqlCoreEnvironment.php, Classes/Core/Acceptance/Helper/AbstractPageTree.php, composer.json
This change updates the dependencies:
* Testing framework now suggests codeception v4 (this is a requirement to allow codeception+phpunit9)
* Testing framework now allows phpunit 8 and phpunit9 as dependency
=> [TASK] Update to codeception v4 and allow phpunit v9

composer.json
Allow both Fluid ^2.5 and ^3 in tested systems.
=> [TASK] Allow use of Fluid 3.0

Classes/Core/Functional/FunctionalTestCase.php
Sometimes it's useful to be able to switch backend user in the test 
(e.g. import data with admin, and then execute test with regular user)
To achieve that a new method is introduced setUpBackendUser which 
sets up backend user which is already in the db.
my case showing usage of the new method:
```
protected function setUp(): void
{
parent::setUp();
//admin user for importing yaml dataset
$this->backendUser = $this->setUpBackendUserFromFixture(1);
Bootstrap::initializeLanguageObject();
$scenarioFile = __DIR__ . '/../../Fixtures/CommonScenario.yaml';
$factory = DataHandlerFactory::fromYamlFile($scenarioFile);
$writer = DataHandlerWriter::withBackendUser($this->backendUser);
$writer->invokeFactory($factory);
static::failIfArrayIsNotEmpty(
$writer->getErrors()
);
//regular editor, non admin …
```
=> Allow switching backend user in the test

Classes/Core/Functional/FunctionalTestCase.php
* Allow switching backend user in the test
Sometimes it's useful to be able to switch backend user in the test 
(e.g. import data with admin, and then execute test with regular user)
To achieve that a new method is introduced setUpBackendUser which 
sets up backend user which is already in the db.
This is a backport of the same change merged in master (https://github.com/TYPO3/testing-framework/pull/171)
=> [TASK] Allow switching backend user in the test (#171)

Classes/Core/Acceptance/Helper/Login.php
Due to issue https://forge.typo3.org/issues/91127 the module "Help >
About" can't be the default anymore, thus the acceptance tests must not
rely on this.
As a replacement, we check whether `div.module` can be found, which
should be sufficient for the intended check.
=> [TASK] Check existence of div.module only

Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php, composer.json
Many functional tests in TYPO3 core currently use
GeneralUtility::getContainer(). This function is marked @internal
and should therefore not be used by third party extensions.
In core we will remove it from functional tests to showcase
best practices. typo3/testing-framework will now provide
FunctionalTestCase::getContainer as API.
Issue on Forge:
https://forge.typo3.org/issues/91363
Related change for TYPO3 core:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/64456
=> [TASK] Provide container instance in functional tests

Classes/Core/Acceptance/Helper/Login.php
When using slower setups or main modules,
the acceptance login suite fails, as it
does not wait for the module frame to fully load.
=> [TASK] Wait for module frame

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
Several properties and methods are unused in TYPO3 v10
and do not need to be instantiated anymore, so they
can be removed.
=> [TASK] Remove unused functionality

Resources/Core/Build/Scripts/splitFunctionalTests.php
The Generator functions (using yield) do not implement the Countable
Interface and therefor are not included into the count function
that evaluates the splitting of existing tests. By retrieving the
count in the Traversable Interface way, the number is now correct.
=> [BUGFIX] Include dataProvider Generators into splitting

Resources/Core/Build/Scripts/splitAcceptanceTests.php
This reverts commit 391f5595f04039dc7e79aa23ac55ef52858da658.
The tests are not picked up by execution, even after they are
included into the splitting.
A stand alone test suite will take care now to execute them, and
the inclusion into split tests action is hereby reverted
=> Revert "[TASK] Add new Acceptance Tests folder to splitter script"

Classes/Core/Functional/FunctionalTestCase.php
This ensures compatibility with TYPO3 v10 and v11.
=> [BUGFIX] Do not set sitetitle to empty value if none is given

Classes/Core/Acceptance/Helper/Login.php
BE login on each and every test adds a small amount of time to
each test setup. Codeception provides a possibility
to save a snapshot of such a session that can be reused, reducing
the set up time for tests.
=> [TASK] Use session snapshots to speed up tests with BE login

Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
Resolving the class loader path by using the public path is unreliable: The vendor folder does not have to be a child of the public folder but can have an arbitrary path. The most reliable and most used class loader path resolution in this extension is based on the fact that this extension itself resides within the vendor folder and thus has a fixed relation to the class loader file.
Resolves: #106, #144
Releases: master
=> [BUGFIX] Fix class loader path resolution in RequestBootstrap

Classes/Core/Acceptance/Helper/AbstractSiteConfiguration.php
In order to test multi language features, we need a more sophisticated
site configuration than the autogenerated one.
=> [TASK] Provide opportunity to write a site config for codeception tests

Classes/Core/Functional/FunctionalTestCase.php
With introduction of Dependency Injection it became obivous, that
ext:backend carries a hard dependency to ext:fluid via the TemplateView.
Usually it is no problem for functional tests, that can define
their dependencies to load. But now the core has a workaround
only for testing framework, so cases without ext:fluid loaded
will not suffer from errors.
=> [BUGFIX] Load ext:fluid for all functional tests

Classes/Core/Functional/Framework/DataHandling/DataSet.php, Classes/Core/Functional/FunctionalTestCase.php
The sys_refindex table has no 'uid' but field 'hash' as primary
key. The patch adds better handling for this in the csv row
assertion rendering.
=> [TASK] Extend csv assertion handling for sys_refindex

Classes/Core/Functional/FunctionalTestCase.php
Having a .csv file with a table name and table field list but
no rows triggers a PHP warning. The patch fixes this to allow
asserting an empty table.
=> [BUGFIX] Allow to csv assert empty table

Classes/Core/Unit/UnitTestCase.php
private properties can not be unset from this scope.
Classes and traits introducing private properties should unset them.
Relates: #178
=> Do not unset private properties in tearDown

Resources/Core/Acceptance/Fixtures/be_users.xml, Resources/Core/Functional/Fixtures/be_users.xml
These fields should not be included in the
test fixtures for backend users, as they
are possibly be removed in TYPO3 v11.0.
=> [TASK] Remove unused fields for BE user fixtures

Classes/Core/Functional/FunctionalTestCase.php
class \Text_Template was available in phpunit/php-text-template
in version 1, but was renamed to \SebastianBergmann\Template\Template
in version 2.
So, using phpunit v9 and composer max conditions, the old class name
is not available anymore and causes failures in functional tests.
=> [BUGFIX] Use renamed class in phpunit v9

Classes/Core/Functional/Framework/DataHandling/ActionService.php
When removing the t3ver_state=1 (planned for TYPO3 v11)
placeholders which are only there to ease the pain
when publishing, the versioned record and the live record
are in fact the same, which should be covered by
the testing framework
=> [BUGFIX] Resolve new versioned records without t3ver_oid

Classes/Core/Functional/Framework/DataHandling/ActionService.php
With commit "d1fc76431dac5d7d41875a4f6a8cc3696963e13e" (#200)
a new check with t3ver_state=-1 was introduced for a proposed
removal of the new placeholder. However, it is planned
to merge "-1" state into "1" within https://review.typo3.org/c/Packages/TYPO3.CMS/+/65587.
For this reason, the change needs to be adapted.
=> [BUGFIX] Use t3ver_state=1 to check for newly created versions

Classes/Core/Functional/Framework/FrameworkState.php, Classes/Core/Functional/Framework/Frontend/InternalRequest.php, Classes/Core/Functional/Framework/Frontend/InternalRequestContext.php, Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php, Classes/Core/Functional/FunctionalTestCase.php, Resources/Core/Functional/Fixtures/Frontend/request.tpl
Add a core v11 compatible method to execute frontend
functional tests as sub request instead of a PHP sub
process. Deprecate the old way.
=> [FEATURE] Frontend functional tests as sub request

Resources/Core/Build/Configuration/JSUnit/Bootstrap.js
lit-html is added to TYPO3 core as client side
template engine. Therefore this library needs
to be loadable in unit tests.
Issue on Forge:
https://forge.typo3.org/issues/91810
Related change for TYPO3 core:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/67092
=> [TASK] Include lit-html/element in JSUnit Bootstrap

Classes/Core/Acceptance/Step/FrameSteps.php
Support scrolling of module menu, page tree and module body in TYPO3
backend during acceptance tests.
The codeception function \Codeception\Module\WebDriver::scrollTo()
fails to do so as it always scrolls the window object of the current
frame and does not allow to specify the exact scrolling element.
Resolves: #214
Releases: master
=> Support scrolling of TYPO3 backend frames in acceptance tests

Classes/Core/Functional/FunctionalTestCase.php
Assigning the DI container as $this->container property in
functional tests introduced quite a memory hog when many
tests are executed.
Test instances are kept in phpunit until end-of-run, so
cleaning up huge objects assigned to test classes is
totally worth it.
A default tearDown() now unsets the container along with
other local properties.
=> [TASK] Unset local variables in tearDown() in functional tests

Classes/Core/Functional/FunctionalTestCase.php
GraphicsMagick is included in default 'runTests.sh'
typo3/core-testing-php images since it adds only a
couple of MB to the image in comparison to
ImageMagick which adds ~100MB.
So we configure functional test TYPO3 instances to
use GM now. This should hopefully have little impact
on existing core and extension tests.
=> [TASK] Use GraphicsMagick for functional tests by default

Classes/Core/Acceptance/Helper/AbstractPageTree.php
Some more recent webdriver detail seems to throw a different
exception when an element is not found. Adapt the page tree
helper to deal with this.
=> [TASK] Prepare for younger selenium-chrome

Resources/Core/Build/Configuration/JSUnit/Bootstrap.js
The javascript modules `@lit/reactive-element` and `lit`
will be available as of Lit v2.
Issue on Forge:
https://forge.typo3.org/issues/93965
Related change for TYPO3 core:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/68104
=> [TASK] Include support for Lit v2 in JSUnit Bootstrap

Classes/Core/Functional/FunctionalTestCase.php
Replaces #230 with a more draconian approach.  The root issue is invalid data that doesn't have a given field.  In that case, the input data is bad and should feel bad, so stop immediately.
This version uses a `ValueError`, because the input data is generally developer provided CSVs and thus a developer problem, not user problem.
=> Explicitly check for valid input data

Classes/Core/Acceptance/Extension/BackendEnvironment.php
codeception needs to bootstrap up until a point where
DB schema migrator can be executed. This automatically
registers the typo3 error handler, which is active when
the test runner executes suites.
This can lead to happy little side effects. Unregister
our custom error handler after DB schema has been created
for system under test.
=> [BUGFIX] Drop TYPO3 custom error handler in ac bootstrap

Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
Hey there,
first of all, many thanks for the `testing-framework` extension, its really great.
On the basis of the work from @alexander-nitsche i backported the changes to the `9` branch. All tests are running fine now with Composer. #144 should be fixed for TYPO3 9.x too.
@bmack Can you please look at the changes?
Thanks for your help.
=> Backported #189 and #190 to `9` branch

Classes/Core/Acceptance/Helper/Acceptance.php
This PR is about firefox / geckodriver support in acceptance tests. The geckodriver does not implement Selenium's logging interface because it is not in the current W3C specifications, and therefore throws an error when trying to access the logs in Acceptance helper. Disable it for geckodriver for now.
This is required for the TYPO3 project https://github.com/TYPO3-Documentation/t3docs-screenshots which aims to replace Chrome with Firefox in perspective.
=> [TASK] Support firefox headless

Classes/Core/Functional/Framework/Frontend/InternalRequest.php
The request implements PSR-7 and therefore allows to call withHeader().
The AssignablePropertyTrait will be used to re build the request based
from serialization.
Headers are internally stored as array with name "headers".
The trait will therefore try to call withHeaders to add the stored
value.
This will break as no such method exists.
The message is added to stay compatible.
Resolves: #238
=> Support withHeader() in InternalRequest

Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
Allow to use other methods beside GET from InternalRequest.
Use defined method.
Also support POST requests with Content-Type
'application/x-www-form-urlencoded'.
Relates: #240
=> Add basic support for none GET requests

Classes/Core/Functional/FunctionalTestCase.php
Functional tests can now set property
protected $initializeDatabase = false;
This skips database creation for test cases that
don't need a database for their system under test.
This is an optimization toggle, tests that can use
this are significantly quicker.
=> [FEATURE] Allow to skip DB setup in functional tests

Classes/Core/Acceptance/Helper/Acceptance.php
This PR is the back-port of PR #242 for TYPO3 v9.
Runs of all acceptance tests of
- TYPO3 v9
with and without this PR showed the same results, so this PR does not introduce regressions.
=> [TASK] Support firefox headless - TYPO3 v9

Classes/Core/Acceptance/Helper/Login.php
This PR is the back-port of PR #250 for TYPO3 v9. It additionally resets the TYPO3 backend user cookies which have been set when bootstrapping the acceptance tests in TYPO3 v9. This reset is not required any longer in TYPO3 v10 and v11.
Runs of all acceptance tests of
* TYPO3 v9
with and without this PR showed the same results, so this PR does not introduce regressions.
Fixes: #235
=> [BUGFIX] Support switching of TYPO3 backend user in Login - TYPO3 v9

Classes/Core/Functional/FunctionalTestCase.php
Provide minimal serverParams array for core v11 compatible frontend subrequest, so the normalized param attributes are set through corresponding frontend middleware, which is needed for some functional tests, ex. PageTypeSuffixDecorator tests.
See https://forge.typo3.org/issues/94537
Resolves #246
=> [BUGFIX] Provide minimal serverParams for Frontend functional subrequest

Classes/Core/Functional/Framework/Frontend/InternalRequest.php, composer.json
This change allows to use guzzlehttp/psr7
in version 2.0 and 1.7+.
=> [BUGFIX] Add compatibility for guzzlehttp/psr7 2.0

composer.json
This helps IDEs like PhpStorm determing the appropriate language level
when opening the testing framework.
- declare a PHP version dependency in the `composer.json`
1. Open the project in PHPStorm.
2. In the lower margin, check the PHP language level.
3. Check that is it "PHP: 7.2" instead of 7.1 or something else.
=> [TASK] Declare a PHP version constraint

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php, Classes/Core/Testbase.php
"Touched" means "the auto increment has been changed (if there is
one)" or "there are some records in it".
This massively speeds up functional tests (as the table truncation
usually is the slowest part of the test setup).
=> [TASK] Only truncate MySQL tables that have been touched

Classes/Core/Testbase.php
This is a follow up to mitigate reliable issues for mysql introduced by #262 .
Using information schema for row counts is not reliable enough for innodb tables, and for mysql 8.0 it fail hard. 
Using subquery as a joinable table building information if tables has at least one row mitigates this issue.
=> [TASK] Only truncate touched MySQL tables using real row counts

Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
sqlite databases are no longer created in
typo3temp/var/tests/functional-"hash"/test.sqlite,
but instead in a parallel directory
typo3temp/var/tests/functional-sqlite-dbs/test_"hash".sqlite.
This allows defining this directory as tmpfs (eg. in runTests.sh),
which significantly improves functional test performance.
Additionally, when the first test created the database schema,
the db file is copied as test_"hash".empty.sqlite. Instead of
truncating the database in consecutive tests of the test case,
the "empty" file is simply copied around to avoid truncate queries.
=> [TASK] Efficient sqlite db handling in functional tests

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseSnapshot.php, Classes/Core/Functional/FunctionalTestCase.php
The db snapshotter is used to increase performance in functional
tests that need heavy lifting like DataHandler operations to prepare
the test set. Consecutive tests of the test case can re-use that snapshot.
The patch changes two details:
* Writing data to both memory and a file is simplified: It now handles
data up to a maximum of 10MB instead of 1MB and uses memory only.
* When using sqlite, instead of dumping rows to memory, the sqlite
file is copied.
This leads to a slight improvement for non-sqlite (less disk I/O) and a
huge improvement with sqlite for tests using the snapshotter.
=> [TASK] Optimize functional DB snapshotter for sqlite

Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
1. Respect header "User-Agent" which might be set in InternalRequest.
Add the following line to the submitted request:
```php
$request = $request->withHeader('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0');
```
Debug the value of `$_SERVER['HTTP_USER_AGENT']`.
Should be the set value, or original as fallback.
Fixes: #256
=> [FEATURE] Support custom user agent in functional tests

Classes/Composer/ExtensionTestEnvironment.php, Classes/Core/Functional/Framework/Package/PackageArtifactBuilder.php, Classes/Core/Testbase.php
Instead of manually disabling Composer mode by
overriding the Environment, create a
PackageArtifact for the desired packages if required
instead of the PackageStates.php file.
=> [BUGFIX] Create PackageArtifact if needed

Classes/Core/Functional/FunctionalTestCase.php
Since PHP 8.1, it's no longer possible to pass `$GLOBALS` by reference.  cf: https://wiki.php.net/rfc/restrict_globals_usage
The functional tests, however, do that on every single subrequest, which causes... a few thousand failures.  Fortunately there's an easy workaround.
(I'm not certain if this fixes all PHP 8.1 issues, but it is certainly the lion's share of them that can be found so far.)
Fixes: #
=> Fix PHP 8.1 compatibility.

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php
Importing snapshotted data through DatabaseSnapshot/DatabaseAccessor
classes records with fixed PK field values (uid) are inserted. For some dbms
platforms this leads to invalid squence values, which errors on further inserts
executed omitting the pk field value (autoincrement insert behaviour).
Thus after inserting the snapshot dataset for a table, reset of table sequence
value is done now to mitigate this issues.
As result one core patch disabled for postgres could be activated again,
which stumpeled into this scenario.
Related core test:
typo3/sysext/frontend/Tests/Functional/SiteHandling/MountPointTest.php
mountPointPagesShowContentAsConfigured
To mitigate the duplicateKey erros reseting sequences after deleting records
solves the issue. 
As such adding existing …
=> [BUGFIX] Reset sequence values after importing snapshotted data

Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
Passing $GLOBALS by reference is not supported since PHP 8.1.
This was fixed for v11 subRequests through #276, but exists for
executeFrontendRequest() also.
So far core master should use new subRequests, this should not be an issue
for core itself. Tests for v11+ must be fixed through as core patch moving
them to new subRequest testing.
Besides this extensions could and are using the testing-framework also for
testing it could be that moving forward to v11, but tests are still on
executeFrontedRequest() calls and not changed to executeFrontendSubRequests(),
and testing on php8.1. Thus this is fixed also, even if executeFrontend() will
be removed in the future from the testing-framework.
Fixes: #277
=> [BUGFIX] Avoid passing $GLOBALS by reference for executeFrontendRequest

Classes/Core/BaseTestCase.php
Similar to a pending core patch [1], the `$originalClassName` parameters of `getAccessibleMock` and `getAccessibleMockForAbstractClass` are annotated as `class-string` and both methods return an object intersecting the incoming class name to enable code completion support in major IDEs.
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/70872
=> [TASK] Add class-string annotation

composer.json
The extension is expected to exist within
`Classes/Core/Functional/FunctionalTestCase.php`.
Some extensions might not require the extension, but use this framework
for functional tests.
They will currently break with exception:
TYPO3\CMS\Core\Package\Exception\InvalidPackagePathException:
Tried to instantiate a package object for package "install"
with a non-existing package path "XXX/typo3/sysext/install/".
Either the package does not exist anymore,
or the code creating this object
The requirement is added to prevent those issues.
1. Add actual hard dependency to sysext install aka typo3/cms-install
Follow steps to reproduce issue in #279
Follow steps to reproduce issue in #279, but use the patched version, e.g. alter `composer.json` of tracking extension:
```diff
diff --git …
```
=> [BUGFIX] Add missing composer dependency to sysext install

Resources/Core/Build/UnitTests.xml
phpunit has changed his behaviour to not throw user depreactions as exceptions per default,
on which the core and eventually extension testings realy on, as it was the default.
To ensure the expected behavour we add convertDeprecationsToExceptions="true"
to the boilerplate *.xml for unittest runs.
Fixes: #282
=> Add phpunit configuration option convertDeprecationsToExceptions

Classes/Core/Functional/FunctionalTestCase.php
Use instancePath as docroot for server request creation, used to add cookie information as beuser initialisation for tests.
=> [TASK] Set instancePath as docroot for createServerRequest

Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php
With change https://github.com/TYPO3/typo3/commit/0c455114f5e8b5a1fff29c128125d923597988a7
it is now possible to inject the $request object,
which should be used in TF as well to ensure
forward-compatibility with v12.
=> [TASK] Inject the request for frontend user auth

Classes/Core/Testbase.php
typo3/sysext/core/bin/typo3 is no longer written
since https://review.typo3.org/c/Packages/TYPO3.CMS/+/71407
when testing-framework is used for extensions.
The patch adapts the path check to frontend index.php.
=> [BUGFIX] Functional test path checks

Classes/Core/Functional/FunctionalTestCase.php
Fix PHPDoc annotation of property type.
1. Reproduce accordingly to issue https://github.com/TYPO3/testing-framework/issues/298
2. Clear cache of PHPStan, e.g. in `/tmp/phpstan`
3. Apply change and try to reproduce again, no errors should be shown this time.
I don't have that setup.
Fixes: #298
=> [BUGFIX] Properly annotate variable type of coreExtensionsToLoad

composer.json
We need to raise this mikey179/vfsstream:~1.6.10 to avoid E_DEPRECATED warnings
in core testing with PHP 8.1 and E_ALL activated in nightly composerMin
test executions.
=> [BUGFIX] Raise mikey179/vfsstream:"~1.6.10"

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Acceptance/Extension/InstallMysqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallPostgresqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallSqliteCoreEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
Constant TYPO3_MODE has been deprecated with core v11
and removed in v12. The patch drops it from functional
and acceptance test setups together with method
Testbase->defineTypo3ModeBe().
=> [!!!][TASK] Don't define TYPO3_MODE anymore

Classes/Core/Functional/FunctionalTestCase.php
This has been a hack for frontend functional test request
handling to keep compatibility with non-sub request handling.
This is removed now.
https://review.typo3.org/c/Packages/TYPO3.CMS/+/72314
=> [TASK] Avoid a compatibilty hack in functional sub request handling

Classes/Core/Functional/FunctionalTestCase.php
TYPO3 core defaults to utf8mb4 charset for MySql
tables since v9.
See: https://review.typo3.org/56440
This allows us to test with unicode characters
with up to 4 bytes.
=> [BUGFIX] Support utf8mb4 charset for MySql tables

Classes/Core/Acceptance/Extension/BackendEnvironment.php
This change is needed to add support for acceptance testing
with sqlite dbms backend, thus give us the ability to start
with it in Typo3 Core Development and for typo3/styleguide.
1. Add switche based sqlite configuration based on database driver to acceptance enviroment
1. See core-patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/72446
The core patch enables sqlite acceptance testing through runTests.sh.
This is currently red, because there are issues in styleguide for sqlite,
so not all needed data is imported - or not correctly.
This change itself is self-containing and do not break currently implementations,
but gives us the ability to get the other pieces working (styleguide), so we can
fix and run core sqlite acceptance tests.
Merging this pull-requets would make it easier to …
=> [TASK] Add support for acceptance sqlite test execution

Classes/Core/DatabaseConnectionWrapper.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
As preparation to raise doctrine/dbal to ^3.2 in core, we need to ensure
that removed things are replaced with corresponding methods. The replacements
are already available in 2.13.x, thus we can replace them beforehand, to stay
compatible with current used version, but have no blocker for the raise.
This pull-requests contains two commits, each commit doing only one thing.
1. Replace `\Doctrine\DBAL\DBALException` with `\Doctrine\DBAL\Exception`
2. Replace `exec()` with `executeStatement()`
> Both commits are marked to be backported to 7 to make future backports
> eventually a little bit easier.
=> [BUGFIX] Avoid deprecated doctrine/dbal exception and method

Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php, Resources/Core/Functional/Extensions/json_response/Configuration/RequestMiddlewares.php
FrontendUserAuthenticator::fetchUserSession() is deprecated in v11 and should
be removed in v12, which is blocked because the json_response frontenduser
middleware uses this method to set signed in frontenduser for testcases
defined over InternalRequestContext.
This commit moves the middleware before core frontend user authentication
middleware and initialize a frontenduser session and inject afterwards
the needed sessionId into the request object, thus avoid to set a real
cookie but still simulate a valid frontenduser session.
Prepares deprecation removal for, tested with patchset 2: 
72476: [!!!][WIP][TASK] Remove deprecated code from Authentication
https://review.typo3.org/c/Packages/TYPO3.CMS/+/72476
=> [TASK] Avoid fetchUserSession() for frontenduser initalization

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseSnapshot.php, Classes/Core/Functional/FunctionalTestCase.php
Database snapshotting is a useful trick to speed up
consecutive tests of a test case if setUp() needs to do
expensive operations to set up the test environment.
It's usage can be simplified down to withDatabaseSnapshot()
by handling snapshot related internals in setUp() directly.
Doing this, FunctionalTestCase::initializeDatabaseSnapshot()
and FunctionalTestCase::destroyDatabaseSnapshot() can be
obsoleted and are marked @deprecated now.
=> [TASK] Simplify DatabaseSnapshot usage in functional tests

Classes/Core/Functional/FunctionalTestCase.php
This commit configures the frontend related caches to
use the NullBackend, which avoids creating corresponding
tables and reduces SELECT and INSERT database statements.
However, some core tests specificly tests against these
tables needs to specify the database backend again to
avoid test failing tests.
Configuration preparation has been prepared as core patch:
72706: [TASK] Use database cache backend for specific tests
https://review.typo3.org/c/Packages/TYPO3.CMS/+/72706
Merging this pull-request should be done with raising the
testing-framework hash in that patch and merging the core
patch shortly after the merge into the testing-framework
to avoid failing nightlies with composerInstallMax tests.
=> [TASK] Configure frontend caches with NullBackend

composer.json
composer 2.2.x checks if plugins are allowed, and if not asks for
confirmation to execute (and add) it.
This change adds the needed allowed plugins to composer.json, which
ensures tests can still run if composer version in core testing images
is raised.
=> [TASK] Add allowed plugins to composer.json

.github/workflows/ci.yml, composer.json
Minimum version for core main has been raised to PHP8.1,
thus failing testing against main development branch if
used PHP <8.1.
* remove PHP7.4 and PHP8.0 from github action matrix
* raise required PHP version to 8.1 in composer.json
used commands:
composer req php:^8.1
=> [TASK] Adjust for minimum php8.1 raise from core main branch

Classes/Core/AccessibleObjectInterface.php, Classes/Core/AccessibleProxyTrait.php
The AccessibleObjectInterface used for
BaseTestCase getAccessibleMock() and
getAccessibleMockForAbstractClass() should
have some syntactic sugar.
Especially _call() should hint for method
arguments to make IDE's more happy.
Strictly speaking, this interface change
is breaking, but consuming tests should not
implement this on its own. We mark the
interface and trait accordingly, now.
=> [!!!][TASK] Modernize AccessibleObjectInterface

Build/Scripts/runTests.sh, Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
This pull-requests contains two self-containing commits
to streamline testing-framework:
1. `[TASK] Streamline Build/Scripts/runTests.sh`
2. `[TASK] Avoid deprecated dbal/doctrine methods`
Both are for `main` only. No backport needed.
testing-framework main has been aligned to core main
requirements. However removing support for older php
versions in `Build/Scripts/runTests.sh` has been missed.
This change removes traces of old php versions from
central `Build/Scripts/runTests.sh` to be aligned
with core again.
Replaces deprecated dbal/doctrine methods with proper
replacements:
* `QueryBuilder->execute()` with `executeQuery()` for
SELECT or COUNT queries (retrieving result set)
* `fetchAll()` with `fetchAllAssociative()`
=> Streamline testing-framework for min php version and avoid deprecated doctrine methods

Classes/Core/Acceptance/Extension/InstallMysqlCoreEnvironment.php, Classes/Core/Acceptance/Extension/InstallPostgresqlCoreEnvironment.php, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
Replace deprecated `Connection::getSchemaManager()` calls with
`Connection::createSchemaManager()` to mitigate deprecation as
early as possible. Deprecation introduced with `doctrine/dbal:^3.x`.
Releases: main
TYPO3 Core: https://review.typo3.org/c/Packages/TYPO3.CMS/+/73629
Styleguide: https://github.com/sbuerk/styleguide/runs/5272006489?check_suite_focus=true
=> [TASK] Replace deprecated doctrine/dbal Connection::getSchemaManager()

Classes/Core/Functional/FunctionalTestCase.php
With FunctionalTestCase being strict_types=1,
renderRecords() needs more type sanitations.
Fixes: #
=> [BUGFIX] Sanitize FunctionalTestCase renderRecords()

Classes/Core/Functional/FunctionalTestCase.php, Resources/Core/Functional/Extensions/private_container/Classes/DependencyInjection/PrivateContainerRealRefPass.php, Resources/Core/Functional/Extensions/private_container/Classes/DependencyInjection/PrivateContainerWeakRefPass.php, Resources/Core/Functional/Extensions/private_container/Configuration/Services.php, Resources/Core/Functional/Extensions/private_container/ext_emconf.php, composer.json
Functional tests frequently need to instantiate $subject
or a dependency. This can be cumbersome if the service
in question is not public, since $this->getContainer()->get()
can currently only instantiate services marked as public.
The patch adds compiler passes as always-registered core
extension to DI in functional tests that allows to get()
private containers, too.
FunctionalTestCase provides access to both, public and
private services via the method `get()`
(as per PSR-11 ContainerInterface). FunctionalTestCase
now implements ContainerInterface in order for static
code analysers like phpstan will be able to resolve
types returned by $this->get(ServiceName::class).
This methods should only be used in the test case
itself. Whenever a service requires a ContainerInterface
argument, the …
=> [FEATURE] Provide access to private services in functional tests

.github/workflows/ci.yml, Build/Scripts/runTests.sh, Build/phpstan/phpstan-baseline.neon, Build/phpstan/phpstan.neon, Build/testing-docker/docker-compose.yml, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php, composer.json
This change adopts phpstan configuration and workflow like it
has been implemented into the core and also typo/cms-styleguide.
* added phpstan/phpstan dev dependency
* added basic phpstan configuration and baseline to 'Build/phpstan'
* added `phpstan` and `phpstan_generate_baseline` container
* added commands to `Build/Scripts/runTests.sh`
- `-s phpstan`
- `-s phpstanGenerateBaseline`
used commands:
```bash
> composer req --dev --no-update \
"phpstan/phpstan":"^1.4.5" \
"codeception/codeception":"^4.1.22"
```
=> [TASK] Have a proper phpstan setup

.github/workflows/ci.yml, Build/Scripts/runTests.sh, Build/phpstan/phpstan-baseline.neon, Build/phpstan/phpstan.neon, Build/testing-docker/docker-compose.yml, composer.json
This change adopts phpstan configuration and workflow like it
has been implemented into the core and also typo3/cms-styleguide.
* added phpstan/phpstan dev dependency
* added basic phpstan configuration and baseline to 'Build/phpstan'
* added `phpstan` and `phpstan_generate_baseline` container
* added commands to `Build/Scripts/runTests.sh`
- `-s phpstan`
- `-s phpstanGenerateBaseline`
* activate in CI
> composer req --dev --no-update "phpstan/phpstan":"^1.4.6"
> composer req --dev --no-update "typo3/cms-workspaces":"10.*.*@dev || 11.*.*@dev"
=> [TASK] Have a proper phpstan setup (#338)

composer.json
testing-framework:7 is a transition version for
extensions that drop v10, keep v11 and add v12.
It should not allow core v10.
> composer req --no-update "typo3/cms-core":"11.*.*@dev"
> composer req --no-update "typo3/cms-backend":"11.*.*@dev"
> composer req --no-update "typo3/cms-frontend":"11.*.*@dev"
> composer req --no-update "typo3/cms-extbase":"11.*.*@dev"
> composer req --no-update "typo3/cms-fluid":"11.*.*@dev"
> composer req --no-update "typo3/cms-install":"11.*.*@dev"
> composer req --no-update "typo3/cms-recordlist":"11.*.*@dev"
> composer req --no-update --dev "typo3/cms-workspaces":"11.*.*@dev"
=> [TASK] Do not allow core v10 in TF 7

Build/phpstan/phpstan-baseline.neon, Classes/Core/Functional/FunctionalTestCase.php
Solve phpstan baseline entry for set_error_handler() with adding
proper type hints to used dummy closure callback method and make
phpstan happier.
=> [TASK] Use proper type hints for set_error_handler() dummy callback

Build/phpstan/phpstan-baseline.neon, Build/phpstan/phpstan-constants.php, Build/phpstan/phpstan.neon, Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php, Classes/Core/Functional/Framework/DataHandling/Scenario/EntityConfiguration.php, Classes/Core/Functional/Framework/FrameworkState.php, Classes/Core/Testbase.php
* add a phpstan bootstrap file to help phpstan with resolving
constants properly.
* set `assignValueInstructions()` argument $value type hint
to mixed to avoid 'PHPDoc tag @param has invalid value'
* Remove superflous assignment of method call with return
type void in `FrameworkState::reset()`
* remove invalid docblock param from `DataHandlerFactory::processEntityValues()`
* avoid unsafe access to private constant in `DataHandlerFactory`
* remove unused class method and sovle one phpstan error.
* use proper docblock for `DataHandlerFactory::$dynamicIdsPerEntity`
* use proper property type-hints in `DataHandlerFactory`
=> [TASK] phpstan level 5 along with minor changes (#342)

Build/phpstan/phpstan-baseline.neon, Classes/Core/Functional/Framework/Frontend/Internal/AbstractInstruction.php
doc-block return type is contrary to native php return type.
This leads to (new) reporting by phpstan which is confused
and interpets this that static(class) should be returned
instead of an instance of class, which is return by using
'new static()' - which is already reported as unsafe.
The implementation of AbstractInstruction and corresponding
child classes can considered safe. This patch removes the
doc-block and add 'phpstan-ignore-next-line' notation to
suppress unsafe warning, which is removed from baseline file.
used command:
> Build/Scripts/runTests.sh -s phpstanGenerateBaseline
=> [BUGFIX] Avoid 'class should return static(class)' for AbstractInstruction

Classes/Core/Functional/Framework/Frontend/InternalRequest.php, Classes/Core/Functional/FunctionalTestCase.php
testing-framework provided methods to call requests using the core
subRequest feature, which was a great overhaul. However, the early
implementation lacked some features, which now bubbles up to the
surface. Extension developers and core could not use the frontend
request to test data submissions with DELETE, PATCH, POST and PUT
http request.
This patch adds the ability to provide 'parsedBody' (_POST) data
set as array with new method 'InternalRequest::withParsedBody()'.
Additional the frontend request emulation has adjusted to properly
build the 'ServerRequest' with the provided 'parsedBody' data.
For 'DELETE', 'POST' and 'PUT' method, body contend will be parsed
to 'parsedBody', if 'parsedBody' data set is set in InternalRequest.
This extends and open new worlds for testing purpose, in …
=> [BUGFIX] Add ability to pass data for POST/PUT/PATCH/DELETE requests

composer.json
- require at least version 1.1.0 to fix a signature mismatch
for `get(string $id)` (which caused a crash with `psr/container`
1.0)
- also allow version 2
This problem was found while running the CI of the Tea example extension with the latest version of the testing framework, but using the lowest possible other dependencies: https://github.com/TYPO3-Documentation/tea/actions/runs/1962922210
=> [BUGFIX] Bump the `psr/container` dependency

Classes/Core/Functional/Framework/Frontend/InternalRequest.php, Classes/Core/Functional/FunctionalTestCase.php
This pullrequest extends InternalRequest from ServerRequest
instead of psr request. Additional the provided prepared
InternalRequest is directly used to handle the frontend
request stack.
Fallback code to prepare some data has been kept.
**Releases:** main, 7
**Gerrit:** https://review.typo3.org/c/Packages/TYPO3.CMS/+/73990
**Note:** Core (Gerrit) patch must be merged after this PR is merged,
to avoid failing core nightly afterwards. Core patch adjusts two tests.
=> [TASK] Directly use InternalRequest instead of new ServerRequest

Resources/Core/Functional/Fixtures/sys_file_storage.xml
The previously set processingfolder starting with typo3temp could be confused with the actual typo3temp folder of TYPO3 which is not the same folder in reality as the folder in this case is a subdirectory of the file storage (fileadmin) in this case.
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/73932 which brought up this confusion.
=> [TASK] Make it clear that processingfolder is not typo3temp

composer.json
As we are using the `PDO` class, we need to have it as an explicit
requirement in order to get a proper warning when the extension
is missing (instead of random breakage).
=> [BUGFIX] Add the PDO PHP extension as a requirement

Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php, Classes/Core/Unit/UnitTestCase.php
This helps developers provide the correct data in their tests, and spot
problems using static analysis more easily.
Also make some type annotations more loose in order to lift
unnecessary restrictions.
=> [TASK] Make the type annotations of the base test classes more specific

Classes/Core/Acceptance/Helper/AbstractModalDialog.php
Since Bootstrap 4 active modals have the "show" class, instead of the "in" class.
This fix restores compatibility with Bootstrap 5 which is used since TYPO3 CMS 11.
Running a test that uses ModalDialog (see example in #375) with TYPO3 CMS 11.
The test should succeed.
Fixes: #375
=> [BUGFIX] Use Bootstrap 5 modal class

Classes/Core/Acceptance/Helper/Acceptance.php, Classes/Core/Functional/Framework/Frontend/Internal/AbstractInstruction.php, Classes/Core/Testbase.php, composer.json
Apply new non-yoda rule.
> composer req --dev typo3/coding-standards:^0.5.3
> Build/Scripts/runTests.sh -p 8.1 -s cgl
The main purpose of this change is to get the build green again.
=> [TASK] Update to typo3/coding-standards:^0.5.3

Classes/Core/Acceptance/Extension/BackendEnvironment.php
In addition to .xml imports, the acceptance test related
BackendEnvironment now allows .csv files to prime the
acceptance test database.
The .csv files are much more slim and easier to read and
maintain. They do not support the EXT: or PACKAGE: prefix
and thus force consumers to provide an own local setup
file: The default fixtures delivered by testing-framework
for current xml imports turned out to be hard to maintain
when core changes db schema, and it's better when extensions
have full control over these files to adapt them to their
needs.
The .xml imports will be deprecated in v6 and v7 with
further patches, and removed in main.
Related: #247
=> [FEATURE] Allow loading csv files in acceptance setup

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Resources/Core/Acceptance/Fixtures/be_groups.xml, Resources/Core/Acceptance/Fixtures/be_sessions.xml, Resources/Core/Acceptance/Fixtures/be_users.xml, Resources/Core/Acceptance/Fixtures/sys_category.xml, Resources/Core/Acceptance/Fixtures/tx_extensionmanager_domain_model_extension.xml
Encourage consumers to switch to csvDatabaseFixtures instead.
The xml import and the fixture files will be dropped in v12
compatible main branch with an additional patch.
Related: #247
=> [TASK] Deprecated acceptance test xmlDatabaseFixtures config

Classes/Core/Functional/FunctionalTestCase.php
The "snapshotter" is handy when priming the database in
setUp() with data in functional tests is expensive. Examples
are the "yaml" scenario core tests that feed DataHandler
with stuff, which takes some time. With the snapshotter,
subsequest tests of the test case are significantly quicker
since they avoid the calculation and just feed DB with records.
Main method withDatabaseSnapshot() takes a callback that is
executed right before *creating* the snapshot. That's the place
where record creation is located.
The patch adds a second callback that is executed just after
snapshots are restored. This allows post-initialization after
restore to for instance set up additional objects.
Additionally, both callbacks are now optional.
=> [FEATURE] Allow restore callback in functional test snapshot

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseSnapshot.php, Classes/Core/Functional/FunctionalTestCase.php
DatabaseAccessor->importTable() and the DB snapshot
functional test expepts the database to be empty when
snapshots are applied.
There was a hack to work around duplicate rows until
now. With the removal of setUpBackendUserFromFixture()
we can now resolve this situation in core usages and
can remove the workaround.
Releases: main
=> [!!!][TASK] DB snapshotter fails on duplicate rows

Classes/Core/Testbase.php
The auto-import of ext_tables_static+adt.sql files in
functional tests is unfortunate in testing-framework
since it creates a non-reliable dependency to potentially
third-party extensions and adds headaches with the snapshot
functionality.
Test cases should instead import needed data using
importCSVDataset(), or call the SchemaManager to apply
static rows from these files on their own.
The patch deprecates this functionality in 6, 7 and main,
another patch will then remove it in main altogether.
Related: #377
Related: #359
=> [TASK] Deprecate auto-import of ext_tables_static+adt.sql files

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Functional/Framework/DataHandling/DataSet.php, Classes/Core/Functional/FunctionalTestCase.php
To avoid code duplication in FunctionalTestCase
with ac test related BackendEnvironment, the body
of importCSVDataSet() is merged as DataSet::import().
=> [TASK] Merge importCSVDataSet() as DataSet::import()

Classes/Core/Functional/Framework/FrameworkState.php
Core v12 will probably drop this property. It is handled
in the FrameworkState class for state reset in functional
tests.
Prepare that class for removal of the property by
catching a ReflectionException that will be thrown
when the property in core is gone.
=> [TASK] Prepare removal of core RootlineUtility::$rootlineFields

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Acceptance/Extension/BackendEnvironmentCodeceptionFive.php, Classes/Core/Acceptance/Extension/BackendEnvironmentCodeceptionFour.php, Classes/Core/Acceptance/Helper/Login.php, Classes/Core/Acceptance/Helper/LoginCodeceptionFive.php, Classes/Core/Acceptance/Helper/LoginCodeceptionFour.php
To support codeception version 4 and version 5 compatibility in
testing against core v11 and core v12 compatibility switches has
been added based on core version. However, neighter core nor the
testing-framework enforces a specific codeception version to be
used for extension or project testing against a specific core
version. The extension or project choose which codeception version
is used for acceptance testing.
To ensure compatibility with codeception version 4 and 5 against
both supported core verion with testing-framework 7 this switch
is changed to detecht the used codeception version instead.
This is still a ugly workaround, but the only way to go.
Releases: 7
=> [BUGFIX] Use codeception change for codeception compat class switch

Build/phpstan/phpstan-baseline.neon, Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
Replaces deprecated dbal/doctrine methods with proper
replacements:
* `QueryBuilder->execute()` with `executeQuery()` for
SELECT or COUNT queries (retrieving result set)
* `fetchAll()` with `fetchAllAssociative()`
> Build/Scripts/runTests.sh -p 8.1 -s phpstanGenerateBaseline
=> [TASK] Avoid deprecated dbal/doctrine methods

Classes/Core/Acceptance/Helper/Login.php, Classes/Core/Functional/FunctionalTestCase.php, Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php
see https://review.typo3.org/c/Packages/TYPO3.CMS/+/69337
Frontend and Backend Cookies are not just the plain session identifier anymore, but the cookie values a hash-signed JWT containing the corresponding session identifier.
=> [!!!][TASK] Use session identifier JWT when initializing sessions

Build/phpstan/phpstan.neon, Classes/Core/Acceptance/Helper/LoginCodeceptionFive.php, Classes/Core/Acceptance/Helper/LoginCodeceptionFour.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Jwt/SessionHelper.php, Classes/Core/Jwt/SessionHelperEleven.php, Classes/Core/Jwt/SessionHelperTwelve.php, Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php
see https://review.typo3.org/c/Packages/TYPO3.CMS/+/69337
This backport contains switches to support TYPO3 v11 and V12 testing in parallel.
FrontendUserHandler middleware is adjusted with v11/v12 switch, dropping v10 switch to align for shifted version testing.
=> [!!!][TASK] Use session identifier JWT when initializing sessions (backport)

Classes/Core/Functional/FunctionalTestCase.php
pagesection cache has been removed in v12 with
https://forge.typo3.org/issues/98503
Resolves: #406
Releases: main
=> [TASK] Remove pagesection cache configuration in functional tests

Build/testing-docker/docker-compose.yml, composer.json
prophecy is no longer a dependency of phpunit.
We can remove a quirk in the test setup again.
We also raise minimum phpunit version to ensure
prophecy is gone, this raise will be left out in
v6 backport.
> composer req phpunit/phpunit:^9.5.25
=> [TASK] Avoid prophecy related composer quirk

Build/php-cs-fixer/config.php, Build/testing-docker/docker-compose.yml, composer.json
typo3/coding-standards is a too big hammer for this tiny repository.
The patch picks the default typo3/coding-standards config and adds it directly.
> composer rem --dev typo3/coding-standards
> composer req --dev friendsofphp/php-cs-fixer:^3.11.0
=> [TASK] Use php-cs-fixer directly

composer.json
doctrine/dbal 2.3.x is not allowed by the core
dependencies anymore, the explicit conflict is
obsolete.
Releases: main
=> [TASK] Remove composer.json conflict with old doctrine

Resources/Core/Functional/Extensions/json_response/Classes/EventListener/AddTypoScriptFromInternalRequest.php
Check for method getRequest() against the event in the event listener instead of undefined variable.
=> [BUGFIX] Use correct class for method_exists check in event listener

Classes/Core/BaseTestCase.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Unit/UnitTestCase.php
This pull-request contains a small chain of commits with
the goal to harden unit and functional tests and has been
verified with:
* [76010: [WIP][TASK] Test testing-framework hardenings](https://review.typo3.org/c/Packages/TYPO3.CMS/+/76010)
This change basicly adds a integrity check to verify
that the `setUp()` call chain of unit tests reaches the
UnitTestCase / BaseTestcase. Prepares also the following
changes.
Core has been checked and fixed with:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/76007
This change introduces a integrity check in the BaseTestCase
to ensure that a test leaves and don't pullate following tests
with changed error_reporting() level state and thus changing
behaviour.
One occurance (and the reason for this check) has been already
fixed in core with: …
=> [!!!][TASK] Tighten unit and functional tests with more checks

Classes/Core/Functional/FunctionalTestCase.php
FunctionalTestCase tearDown() got recently the order to proper
cleanup written site configurations and the corresponding core
cache. Howver, some developers may use the provided property
`array $pathsToLinkInTestInstance[]` to define a folder which
should be symlinked as site-configuration instead of writing
them. The new order now removes these site-configuration files,
thus missing them on subsequence tests.
This change introduces some checks to only cleanup, if the folder
and files a dedicated to the instance and not symlinked (folder).
=> [BUGFIX] Avoid removing site configuration if folder is symlinked

Resources/Core/Functional/Extensions/json_response/Configuration/RequestMiddlewares.php
typo3/testing-framework frontend-user injection using the corresponding InternalContext setting for the user id *must* be proper set, before the core frontend-user authenticator middleware evaluates and loads the needed informations.
This change adjusts the middleware loading definition of testing-framework FrontendUserHandler middleware to ensure the correct loading order.
Resolves #424
Releases: 7
=> [BUGFIX] Load frontend-user injection middleware before FE authenticator

Classes/Core/Functional/Framework/FrameworkState.php
Static properties, mainly the static caches and the static
property has been made obsolete on RootlineUtility. This
avoids nasty and shitty state on the RootlineUtility, thus
making it superflous to guard the state of these static
properties with the FrameworkState service class.
This change checks for the presence of the `purgeCache()`
method of the `RootlineUtility`, and only doing the well
known guarding of RootlineUtility if this method is still
present. This should be removed with next major version.
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/76637
and https://review.typo3.org/c/Packages/TYPO3.CMS/+/76638
=> [TASK] Deal with eventual absent RootlineUtility properties

Classes/Core/Functional/Framework/FrameworkState.php
FrameworkState::* methods are used to save the state before
executing frontend sub requests in functional tests. This
contained handling static caches of the the `RootlineUtility`.
These static property caches has been recently removed in TYPO3,
along with the then obsolete static method `purgeCaches()`.
Thus FrameworkState has been changed to only handle the static
cache handling of `RootlineUtility` if method `purgeCaches()`
exists. That check has been wrapped in a dedicated static method.
PHPStan now have issues to properly recognise that the call to
`RootlineUtility::purgeCaches()` is only called, if existing.
To mitigate this, this change removes the static wrap-method and
doing the `method_exists()` check in the three methods directly.
=> [TASK] Let phpstan properly detect that called method exists

Classes/Core/Acceptance/Extension/BackendEnvironmentCodeceptionFive.php, Classes/Core/Acceptance/Extension/BackendEnvironmentCodeceptionFour.php, Classes/Core/Functional/FunctionalTestCase.php
With https://review.typo3.org/c/Packages/TYPO3.CMS/+/76553
support for native json database field has been introduced 
into TYPO3. This came along with automatic transformation 
from PHP-Value to database compatible values, which basicly 
means that the values get json-encode'd.
Providing fixture database values for JSON fields are now 
impossible to set, as string values get encoded as string
which does not write the expected values to the database.
This change uses the already used database schema information
and proper decode the values after reading from the csv files.
That ensures that the data written to the database has the
expected format. Othewise testing would be inpossible for
JSON-Fields.
=> [TASK] Ensure fixture field data for json fields can be inserted

Tests/Unit/Core/Fixtures/Json/WithJsonValueQuotedWithDoubleQuotes.csv, Tests/Unit/Core/Functional/Framework/DataHandling/DataSetTest.php
Add a test to ensure that fixture csv json string is
read in a way that it can be properly decoded.
=> [TASK] Add DataSet to ensure json value string can be decoded

Build/phpstan/phpstan-baseline.neon, Classes/Core/BaseTestCase.php, Classes/Core/Functional/FunctionalTestCase.php
This change adds a exception with a proper exception message, if 
`executeFrontendSubRequests()` is used with invalid core version.
As a side fix a string cast is added to avoid phpstand error
reporting because of type missmatch.
Used command(s):
```shell
Build/Scripts/runTests.sh -s phpstanGenerateBaseline
```
Resolves #437
=> [TASK] Guard "executeFrontendSubRequests()" against old core version

Build/phpstan/phpstan-baseline.neon, Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php, Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerWriter.php, Classes/Core/Functional/Framework/DataHandling/Scenario/EntityConfiguration.php, Classes/Core/Functional/Framework/Frontend/ResponseContent.php
See [1]. I hesitant declaring the entire classes
final at the moment, but final __construct()
should be fine for now.
[1] https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static
=> [TASK] Avoid phpstan "Unsafe usage of new static()"

Build/phpstan/phpstan-baseline.neon, composer.json
To prepare core and extension towards phpunit 10,
we need to allow it in TF as a first step:
$ composer req phpunit/phpunit:"^9.5.25 || ^10.0.14" $ Build/Scripts/runTests.sh -s phpstanGenerateBaseline
Issues will be sorted out with further patches.
=> [TASK] Allow phpunit ^10 next to ^9

Classes/Core/Unit/UnitTestCase.php
When a test uses GeneralUtility::addInstance() to add (non-singleton) instances, and if that test does not consume all those instances, it fails.
The patch adds a call to clean up left over instances. This way, tests executed afterwards start clean again and don't fail as side-effect as well anymore.
Releases: main
=> [TASK] Consecutive tests do not fail on left over instance

Classes/Core/Functional/Framework/FrameworkState.php, Classes/Core/Unit/UnitTestCase.php
setAccessible() is a no-op since PHP 8.1.
We can clean up the FrameworkState class
quite a bit: core RootlineUtility
switched to runtime caches meanwhile.
Releases: main
=> [TASK] Avoid setAccessible()

Build/phpstan/phpstan-baseline.neon, Classes/Core/BaseTestCase.php
setMethods() has been removed with phpunit 10.
$this->getAccessibleMock() used this to only
partially mock a test subject. The patch switches
to onlyMethods() now.
There is one difference: onlyMethods() fails if
a methods that should be mocked does not exist,
while setMethods() did not fail on this.
So this is more strict now. It was frequently used in core tests mocking ['dummy'] to say "mock no method". Those have to be switched to use 'null' as argument to $this->getAccessibleMock() now. Also, when a class is refactored, and a method that has been previously mocked is removed with the refactoring, the mock has to be adapted to remove the method-mock request from the test as well now, otherwise the test will fail.
Resolves: #444
=> [TASK] Avoid setMethods() on mocks

Classes/Core/BaseTestCase.php
setMethods() has been removed with phpunit 10.
$this->getAccessibleMock() used this to only
partially mock a test subject. The patch switches
to onlyMethods() now.
There is one difference: onlyMethods() fails if
a methods that should be mocked does not exist,
while setMethods() did not fail on this.
So this is more strict now. It was frequently used in core tests mocking ['dummy'] to say "mock no method". Those have to be switched to use 'null' as argument to $this->getAccessibleMock() now. Also, when a class is refactored, and a method that has been previously mocked is removed with the refactoring, the mock has to be adapted to remove the method-mock request from the test as well now, otherwise the test will fail.
Rules for the second argument of getAccessibleMock():
* "keep all …
=> [!!!][TASK] Avoid setMethods() on mocks

Classes/Core/Unit/UnitTestCase.php
With core unit tests, avoiding the property clean
up code in UnitTestCase tearDown() actually
reduces memory usage by now. This might be a
side effect of more clean unit tests, and it
seems the PHP reflection can be a bit of a
memory hog.
We'll remove that code for now.
Releases: main
=> [TASK] Do not clean up properties in UnitTestCase tearDown()

Classes/Core/Testbase.php
Creating symlinks in `Testbase` may fail due several
reasons, triggering a mostly use-less message without
much context.
This change now uses the `@` silence operator for the
`symlink()` method calls in `Testbase` in favour of
the more use-full custom error message provided by the
thrown exceptions.
Resolves: https://github.com/TYPO3/testing-framework/issues/456
=> [BUGFIX] Silence `symlink()` errors using `@` operator 

Classes/Composer/ComposerPackageManager.php, Classes/Composer/PackageInfo.php, Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/SystemEnvironmentBuilder.php, Classes/Core/Testbase.php, Resources/Core/Build/UnitTestsBootstrap.php, composer.json
Since TYPO3 v12.0 the "typo3/cms-composer-installers" package
is a hard requirement in version 5. This comes along with some
changes:
* system-extensions are no longer installed in
`<public-dir>/typo3/sysext/*`
* extensions are no longer installed in
`<public-dir>/typo3conf/ext/*`
Extension and System Extensions are now installed into the
`vendor-dir` folder, which is the default behaviour of the
composer package-manager. Generally, this is really good
move.
"typo3/testing-framework" expected a specific setup structure,
to provide correct symlinks for system and extensions for
functional- and acceptance test instances. Which is not given
anymore.
As a intermediate solution, a composer plugin has been put
into the wild, providing the the expected structure with
symlinks. Which is a …
=> [TASK] Ensure "typo3/cms-composer-installers" v5 compatibility

Classes/Core/Functional/FunctionalTestCase.php
With c34df68, symlinks of framework extensions such as `json_response` were removed (see https://github.com/TYPO3/testing-framework/commit/c34df68427475543e9a73d337824241a40b382cd#diff-8cfe230a7b65db0044a7b32148784e47da3e6521474a51d16ceaba06636b1363L326). Without the symlinks, all fixture extensions provided by TF are no longer available in the test application, making it impossible to perform e.g. internal requests.
This PR reactivates symlinks of configured framework extensions, restoring the original behavior and re-enabling usage of internal requests in functional tests.
Related: #435
Releases: 7
=> [BUGFIX] Reactivate framework extensions in functional tests

.gitignore, Build/phpstan/phpstan.neon, Build/testing-docker/docker-compose.yml, Classes/Composer/ComposerPackageManager.php, Classes/Composer/PackageInfo.php, Classes/Core/Testbase.php, Tests/Unit/Composer/ComposerPackageManagerTest.php, Tests/Unit/Composer/Fixtures/Extensions/ext_absolute/composer.json, Tests/Unit/Composer/Fixtures/Extensions/ext_absolute/ext_emconf.php, Tests/Unit/Composer/Fixtures/Extensions/ext_fallbackroot/composer.json, Tests/Unit/Composer/Fixtures/Extensions/ext_fallbackroot/ext_emconf.php, Tests/Unit/Composer/Fixtures/Extensions/ext_relativefromroot/composer.json, Tests/Unit/Composer/Fixtures/Extensions/ext_relativefromroot/ext_emconf.php, Tests/Unit/Composer/Fixtures/Extensions/ext_relativelegacy/composer.json, Tests/Unit/Composer/Fixtures/Extensions/ext_relativelegacy/ext_emconf.php, Tests/Unit/Composer/Fixtures/Extensions/ext_without_composerjson_absolute/ext_emconf.php, Tests/Unit/Composer/Fixtures/Extensions/ext_without_composerjson_fallbackroot/ext_emconf.php, Tests/Unit/Composer/Fixtures/Extensions/ext_without_composerjson_relativefromroot/ext_emconf.php
> BACKPORT of #467
Several issues and headaches have been reported. For example:
* TYPO3 v11 composer minor with <11.5 failed due not existing PathComponent in `symfony/filesystem` in that low version
* Test extension (root) using `typo3conf/ext/extension_key` did not worked
* Test fixture extension loading did not worked, e.g. `typo3conf/ext/extension_key/Some/Paths/test_extension`
* Test extensions without a `composer.json` no longer could loaded (TF7 for v11 and composer installers 3)
* Test extensions with some relative folder names did not resolved properly
Therefore, several patches have been implemented in chain to tackle these issues and improve the overall handling and compat high, minimizing the need for "test case" adoptions.
See each commit message for more detailed …
=> [TASK] Backport of #467 ( cms-composer-installers enhancement)

Build/phpstan/phpstan-baseline.neon, Classes/Composer/ExtensionTestEnvironment.php
With https://github.com/TYPO3/testing-framework/pull/307 symlinking of the root package extensions is no
longer handled by the testing-framework composer script for
TYPO3 v11 based testing environments. This has been shifted
to the core.
TYPO3 v11 core implemention do no longer symlink root package
extensions to the extension folder, if no `Resources/Public/`
resources exists in the extension.
This change reverts the no-op check and let the root package
extension be symlinked again, in all circumstances.
This avoids this edge case.
**Note** TYPO3 v11 testing using `typor/cms-composer-installers`
version 4RC1 is still not supported. Switch to TF7+ for support.
Used command(s):
```shell
Build/Scripts/runTests.sh -s phpstanGenerateBaseline
```
Releases: 6
Related: …
=> [TASK] Ensure root package extension is symlinked

Classes/Core/Functional/FunctionalTestCase.php
With ODBC v18 Microsoft decided to make 'Encrypt=Yes'
the default, which breaks automatic testing using the
linux mssql server. Since PHP 8.0.27 the v18 client
library is used instead of the v17, introducing this
change.
Setting `Encrytion` to false(no) to mitigate this issue
meanwhile.
Resolves: #433
Releases: 7, 6
=> [BUGFIX] Set `Encrypt=No` for sqlsrv and pdo_sqlsrv

Classes/Core/Functional/FunctionalTestCase.php
The patch configures frontend related caches to ese the
NullBackend in functional tests. This avoids creating corresponding
tables and reduces SELECT and INSERT database statements.
This results in a performance increase running frontend functional
tests, with core, this is around 5-10% when using postgres DMBS.
Late backport of e45ee97112096c5a902093cc9e2a4c07af1cb49e
=> [BACKPORT][TASK] Configure frontend caches with NullBackend (#321)

Classes/Core/Functional/Framework/DataHandling/DataSet.php
The testing-frameworks provides the ability to read csv fixture
files to import database datasets. The internal `DataSet::import()`
implementation is provided by `FunctionalTestCase->importCSVDataSet()`.
Sometimes duplicate rows with the same identifier (`uid` or `hash`)
are included in a csv dataset file which are overriden.
This change now checks during the dataseet import phase for these
duplicates and throw a exception stating the table and id value
to make the usage easier and helps with finding test-setup issues.
Note: `assertCSVDataSet()` counter part will not check for duplicates.
Resolves: #478
=> [TASK] Detect duplicate table records within `importCSVDataSet()`

Classes/Core/Functional/Framework/FrameworkState.php
With PHP8.3 the `ReflectionProperty->setValue()` method
emits a E_DEPRECATED if a value should be set to a class
and the context is not set as first argument.
For instanciated classes the class needs to be provided,
which is not possible for a static class or property.
The solution for this is to use `null` as first argument
as context object. That avoids the deprecation and keeps
the backward compatibility.
The testing-framework provides a tool to keep and handle
static Framework state, which uses reflection under the
hood and therefore needs the null context for `setValue()`.
=> [TASK] Avoid php deprecation in FrameworkState (7)

Classes/Core/Functional/Framework/FrameworkState.php
With PHP8.3 the `ReflectionProperty->setValue()` method
emits a E_DEPRECATED if a value should be set to a class
and the context is not set as first argument.
For instanciated classes the class needs to be provided,
which is not possible for a static class or property.
The solution for this is to use `null` as first argument
as context object. That avoids the deprecation and keeps
the backward compatibility.
The testing-framework provides a tool to keep and handle
static Framework state, which uses reflection under the
hood and therefore needs the null context for `setValue()`.
=> [TASK] Avoid php deprecation in FrameworkState (6)

Classes/Core/Functional/Framework/DataHandling/DataSet.php
A DB column value "0" is a perfectly valid value and should not be considered to be empty.
Particularly, having a "0" value as the first value in a DB row in a CSV file should still allow the DB row to get importet.
(In general, `empty()` in PHP behaves in mysterious ways and should be avoided in favor of more explicit and human-predicable checks.)
Fixes #488
=> [BUGFIX] Do not consider "0" as empty in the CSV DB import

Classes/Core/Functional/Framework/DataHandling/DataSet.php, Classes/Core/Functional/FunctionalTestCase.php
This avoids false positives in cases where PHP would cast values.
=> [TASK] Make all `in_array` calls strict

Classes/Core/Unit/UnitTestCase.php
TYPO3 v12 and v13 removes this property, so it can't be reflected anymore. Current main/v8 TF should remove this, while v7 (core v11 & v12) should implement a fallback.
=> [TASK] Expect LocalizationUtility::configurationManager is gone

Classes/Core/Unit/UnitTestCase.php
Property LocalizationUtility::configurationManager has been removed in core v12 and main. We can skip the reflection hack in UnitTestCase::tearDown() now.
Related: https://forge.typo3.org/issues/101779
Releases: main
=> [TASK] Remove configurationManager reflection in UnitTestCase

Classes/Core/BaseTestCase.php
This method uses `getMockForAbstractClass()` under the hood, which in turn has been soft-deprecated in PHPUnit 10.1 and will issue deprecation warnings in PHPUnit 11 and up:
https://github.com/sebastianbergmann/phpunit/issues/5241
Releases: main
=> [TASK] Deprecate `getAccessibleMockForAbstractClass`

Classes/Core/Testbase.php
Can be removed again when next core v12
patch level has been released.
Resolves: #498
=> [BUGFIX] Have compat hack for SchemaMigrator

Classes/Core/Acceptance/Helper/Acceptance.php
The chrome option `--unsafely-treat-insecure-origin-as-secure`
seems to not working in all cases during acceptance tests in
the core. JavaScript errors like following example are still
emitted and leading in some circumstances to test failures:
```
The file at 'http://web/typo3/record/download?token=sometoken'
was loaded over an insecure connection. This file should be
served over HTTPS.
```
Furthermore, the testing-framework provides an `isJsError()`
check which is executed after each step.
This change now ignores such insecure errors like the already
included `ERR_PROXY_CONNECTION_FAILED` check. `strpos()` are
replaced with more readable `str_contains()` checks.
Releases: main
=> [TASK] Ignore insecure file download JavaScript errors

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Acceptance/Helper/Login.php
A concrete `wait()` is added before waiting for the
login ready state for creating a user session. The
wait time is increased for retries.
Releases: main
=> [TASK] Stabilize `Login->useExistingSession()` for webserver

Classes/Core/Acceptance/Helper/Login.php
The waitTime used in `Login->useExistingSession()` is
now configurable. This allow extensions to adjust the
waitTime to stabilize tests.
Releases: main
=> [TASK] Make `Login->useExistingSession()` waitTime configurable

Classes/Core/PackageCollection.php, Classes/Core/Testbase.php
The new `PackageCollection` uses the behavior of the `PackageManager` to define proper dependency ordering of extensions when executing functional and acceptance tests.
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81076
Releases: main
=> [TASK] Ensure package dependencies in functional/acceptance tests

.github/workflows/ci.yml, Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php, Classes/Core/Functional/FunctionalTestCase.php
Database name only allows a special set of characters.
Based on the configured database name, functional test
creates databases per functional test case.
Due to the general policy the typo3/testing-framework
should not silently fix setup errors. Therefore, invalid
database name configuration is now detected, throwing a
`\RuntimeException` with a use-full exception message.
=> [TASK] Avoid invalid database name configuration

Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/FunctionalTestCase.php, composer.json
This change replaces the `\PDO::PARAM_*` constants with the TYPO3
`\TYPO3\CMS\Core\Database\Connection::PARAM_*` alternatives. This
aligns the testing-framework with the core and the communicated
best-practice.
The direct dependency to `ext-pdo` is removed right away.
Note: `doctrine/dbal 4+` dropps support for the \PDO integer constants.
Using the `Connection` constants allows us to change the mapping
in that class and consuming code, like extensions or this package
automaticlly uses the correct enum class on upgrade.
Used command(s):
```shell
composer remove ext-pdo
```
=> [TASK] Replace `\PDO::PARAM_*` constants with `Connection::PARAM_*`

Classes/Core/Testbase.php
The doctrine team deprecated the `AbstractSchemaManager::getDatabasePlatform()`
method has been deprecated. [1]
Use `Connection::getDatabasePlatform()` instead to mitigate this deprecation.
[1] https://github.com/doctrine/dbal/blob/3.7.x/UPGRADE.md#deprecated-abstractschemamanagergetdatabaseplatform
Releases: main
=> [TASK] Avoid deprecated `AbstractSchemaManager::getDatabasePlatform()`

Classes/Core/PackageCollection.php, Classes/Core/Testbase.php
The testing-framework creates test instances per
functional test-case based on properties defining
the system extensions, extension and fixture test
extension to symlink and load in the non-composer
test instances.
Therefore, the `PackageStates.php` file is created
on the first test run per test-case manually based
on the provided properties in the defined order.
With [1] a `PackageCollection` class has been added
to ensure proper extension sorting in the packages
state file based on dependency informations. That
is essentially for the loading and processing order.
Since TYPO3 v12 extensions in composer mode no longer
requires the presence of a `ext_emconf.php` versus
non-composer mode. The `ext_emconf.php` is still added
if a extension is published to TER. Therefore, some
extension …
=> [BUGFIX] Ignore non-typo3 packages in PackageState 

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseSnapshot.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
The doctrine team deprecated the `getName()` method
for platform classes within `doctrine/dbal 3.x` [1].
This change modifes userland code to
a) replace `getName()` with `instanceof` checks
Using `instanceof` checks against the connection platform
is the propose replacement for the deprecated `getName()`
method.
b) Use prefixed class namespace alias for imported platforms
Instead of
use Doctrine\DBAL\Platforms\SqlitePlatform;
prefixed alias is used:
use Doctrine\DBAL\Platforms\SqlitePlatform
as DoctrineSQLitePlatform;
Only caveat is, that static code analysers like PHPStan
may report it.
[1] https://github.com/doctrine/dbal/blob/3.7.x/UPGRADE.md#deprecated-abstractplatformgetname
Releases: main
=> [TASK] Avoid calling deprecated `Platform->getName()`

Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseSnapshot.php, Classes/Core/Testbase.php
* [1] Doctrine DBAL 4 removed `SqliteManager->createDatabase()`
and `SqliteManager->dropDatabase()`. The engine is createing
the SQLite file on connect, but do not remove it on close.
The `Testbase->setUpTestDatabase()` code is modified to delete
the sqlite file directly, and let the engine handle the sqlite
file creation on connect.
* [2] Doctrine DBAL 4 changed the casing of some classes, for
exmaple `SqlitePlatform` to `SQLitePlatform`, which is not an
issue for code execution due to the case-insensitive nature of
PHP - but static code analyser tools like PHPStan fall on their
feed. Therefore, we use minor wrapping methods instead of php
interfaceof checks directly to mitigate this and avoid jumping
PHPStan baseline entry until Doctrine DBAL 4 is the minimal to
support version.
Note: …
=> [TASK] Ensure Doctrine DBAL 3 and 4 dual support

Classes/Core/Acceptance/Helper/Login.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/SystemEnvironmentBuilder.php, Classes/Core/Testbase.php, Resources/Core/Build/UnitTestsBootstrap.php
/typo3/index.php is deprecated and must not longer be used.
See https://forge.typo3.org/issues/87889 and
https://review.typo3.org/c/Packages/TYPO3.CMS/+/74366
Releases: main
=> [TASK] Use /index.php as application entry point

Classes/Core/Testbase.php
Functional tests per nature speaks with a concrete database service,
which can be configured using a et of `environment variables`.
However, historically a fallback to `typo3conf/LocalConfiguration.php`
or the root project has been used if no environment variable has been
provided.
This broke already in early TYPO3 v12 development cycle with the
move towards configuration files outside of the public root folder
in a composer based installation.
Because of today usage of the testing-framework and the broader
acceptance of ci/cd pipelines the environment variables are the
recommended configuration option. Remove the broken fallback now.
Resolves: #474
Releases: main
=> [TASK] Remove functional test database configuration fallback

.github/workflows/ci.yml, Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseSnapshot.php, Classes/Core/Testbase.php
It seems that `@phpstan-ignore-next-line` mumbles when it does non actively suppress something. With the release of doctrine 4, this kicks in for two lines which phpstan gets right now.
phpstan with PHP 8.2 now collides with 8.1, we skip the 8.1 run. Also add PHP 8.3 to the matrix.
=> [TASK] Happify phpstan again

Classes/Core/Functional/FunctionalTestCase.php
Setting TS constant 'databasePlatform' for tests that require TS setup is a relict from the past and can be removed.
=> [TASK] Avoid obsolete TS constant

composer.json
TF itself has no hard dependency to typo3/cms-install.
> composer rem typo3/cms-install
=> [TASK] Do not hard require typo3/cms-install

.github/workflows/ci.yml
GitHub action does not respect configured
schedules (cron) on non-default branches.
This change now removes the schedule definition
and adds a `workflow_dispatch` definition along
with a branch logout in the workflow, which acts
as a preparation for dispatched scheduled run
from the default branch later.
=> [TASK] Remove scheduled workflow from branch `7`

.github/workflows/ci.yml
GitHub action does not respect configured
schedules (cron) on non-default branches.
This change now removes the schedule definition
and adds a workflow_dispatch definition along
with a branch logout in the workflow, which acts
as a preparation for dispatched scheduled run
from the default branch later.
Note: Scheduled runs for main and version branch
will be reintrodued with a followup change using
a dedicated workflow file.
=> [TASK] Remove scheduled workflow from branch `main`

.github/workflows/nightly-7.yml, .github/workflows/nightly-main.yml
This change reintroduces scheduled
ci exectution. In contrast to the
prior setup the used way allows us
to have schedules not only for the
default branch.
As a side-effect we get the ability
to manually dispatch nightly on a
branch any time.
=> [TASK] Reintroduce scheduled nightly

Classes/Core/Functional/Framework/DataHandling/DataSet.php, Classes/Core/Functional/FunctionalTestCase.php
When importing a .csv with a table definition and
no rows, a warning is raised: DataSet->getElements() may return null, and this fails in the foreach in
DataSet->import(). It is more clean to return an
empty array in getElements(), which is done with
the patch.
=> [BUGFIX] Allow importing empty CSV table

Classes/Core/BaseTestCase.php
Remove two obsolete exceptions - empty string will throw in \ReflectionClass by PHP.
=> [TASK] Happify phpstan

Classes/Core/Functional/FunctionalTestCase.php
Recent phpunit 10.5 and 11.2 versions improved internal memory handling significantly. This obsoletes the
dedicated unset() calls we had in tearDown() of
functional test cases.
=> [TASK] Avoid no longer needed unset() in tearDown()

Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/Testbase.php
TF 8.1.0 removed 'composer req' of typo3/cms-install. Extension functional tests may now fail when trying to create the 'install.php' link - the file no longer exists if the extension itself has no requirement to typo3/cms-install, which most extensions don't have.
Resolves: #566
=> [BUGFIX] Check for install.php existance

Build/Scripts/runTests.sh
--path-mode intersection without default option
leads to php-cs-fixer scanning nothing. Remove
option and just let scan everything always.
=> [TASK] php-cs-fixer scans again

Build/phpunit/UnitTests.xml
Unit tests of TF itself don't need custom boostrap, and backupGlobals=true isn't needed either. Clean
up the xml file.
=> [TASK] Clean up phpunit setup

Build/Scripts/runTests.sh
Fix cleanUp() to properly shut down networks
after run.
=> [TASK] runTests.sh removes networks after run

Classes/Core/BaseTestCase.php
This is based on phpunit deprecated getMockForAbstractClass() and has been marked deprecated with testing-framework 8. Remove it now.
=> [!!!][TASK] Remove getAccessibleMockForAbstractClass()

Classes/Core/BaseTestCase.php
Remove a fallback in BaseTestCase->shouldErrorHandlerBeUsed()
=> [TASK] Avoid compat layer for old phpunit versions

Classes/Core/Functional/FunctionalTestCase.php
Method FuncionalTestCase->assertCSVDataSet(string $fileName) always needs an absole path. A typical solution is relative to current test case like
$this->assertCSVDataSet(__DIR__ . '/Fixtures/some.csv') to resolve properly. A syntax like 'EXT:...' is no longer resolved.
=> [!!!][TASK] FuncionalTestCase->assertCSVDataSet() needs abs path

Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerWriter.php
To prepare DH for DI, consumers must use core
instance factory method instead of new().
=> [TASK] Create DataHandler using GU::makeInstance()

Classes/Core/Functional/FunctionalTestCase.php
This change modifies the `FunctionalTestCase` and extract
database setup related code into two dedicated internal
methods:
* initializeTestDatabase()
* initializeTestDatabaseAndTruncateTables()
Note that these are marked as internal but needs to be
kept `protected` to allow one special testcase in the
TYPO3 core [1].
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/84942
=> [TASK] Extract some details from `FunctionalTestCase::setUp()`

Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerWriter.php
To prepare DH for DI, consumers must use core
instance factory method instead of new().
=> [TASK] Create DataHandler using GU::makeInstance() (#602)

Build/php-cs-fixer/config.php, Classes/Composer/ComposerPackageManager.php, Classes/Core/BaseTestCase.php, Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/Frontend/Collector.php, Classes/Core/Functional/Framework/Frontend/ResponseContent.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/PackageCollection.php
Implicit nullable method parameters are deprecated with PHP 8.4. The patch prepares affected method
signatures and activates an according php-cs-fixer rule.
=> [TASK] Avoid implicitly nullable method parameter

Build/php-cs-fixer/config.php, Classes/Core/Functional/Framework/AssignablePropertyTrait.php, Classes/Core/Functional/Framework/DataHandling/ActionService.php, Classes/Core/Functional/Framework/DataHandling/CsvWriterStreamFilter.php, Classes/Core/Functional/Framework/DataHandling/DataSet.php, Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php, Classes/Core/Functional/Framework/Frontend/Collector.php, Classes/Core/Functional/Framework/Frontend/Renderer.php, Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php, Classes/Core/Functional/Framework/Frontend/ResponseContent.php, Classes/Core/Functional/FunctionalTestCase.php
Implicit nullable method parameters are deprecated with PHP 8.4. The patch prepares affected method
signatures and activates an according php-cs-fixer rule.
=> [TASK] Avoid implicitly nullable method parameter (#896)

Classes/Core/Testbase.php
The `Testbase->setUpTestDatabase()` takes care of
correct database setup for each test instance and
that the database is created. To accomplish that,
current TYPO3 connections are closed.
Doctrine DriverManager is used as lowlevel tool
to create the instance database.
In case that the database has not been created,
which occures on the first test execution per
test-case, an exception is thrown and disturbes
the `getDatabasePlatform <-> getServerVersion()`
detection with the Doctrine construct. That has
been mitigated by catching the exception within
`Connection->getServerVersion()` and returning
an empty string ending up retrieving at least a
the lowest default platform for the driver. That
was mainly a workaround in functional test runs.
Doctrine DBAL 3.9.x & 4.1.x will introduce a new …
=> [TASK] Streamline `Testbase->setUpTestDatabase()`

composer.json
TF needs this since core monorepo removed the copy of ClassMapGenerator with [1] for functional test
legacy instances of extensions.
> composer req composer/class-map-generator:^1.3.4
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/86184
=> [TASK] composer req composer/class-map-generator:^1.3.4

Classes/Core/Functional/Framework/DataHandling/DataSet.php
With [1] the 5th parameter `$escape` of `fgetcsv()` must
be provided either positional or using named arguments or a
E_DEPRECATED will be emitted since `PHP 8.4.0 RC1` [2].
This change provide now all five parameter for `fgetcsv()`
calls and thus using the positional approach to allow easier
backporting to older TYPO3 version where named arguements are
not usable.
[1] https://github.com/php/php-src/pull/15569
[2] https://github.com/php/php-src/blob/ebee8df27ed/UPGRADING#L617-L622
Releases: main, 8, 7
=> [TASK] Explicitly provide all `fgetcsv()` arguments

Classes/Core/Acceptance/Helper/AbstractPageTree.php
This changes all property accesses within AbstractPageTree to use static instead of self. Since the class is abstract and therefore subject to class inheritance, its properties may also change in subclasses. Using self to access them would hide potentially overridden properties (late static binding).
=> [BUGFIX] Respect overridden properties in AbstractPageTree

Classes/Core/Acceptance/Helper/AbstractPageTree.php
Even if page tree nodes are queried from a given context node, the used XPath query searches for all elements in the document because of the `//` syntax. This may lead to possible test failures in case the queried node text appears multiple times in the document.
In order to avoid such behaviors and actually limit the XPath query to the given context, it is now prefixed with a dot (`.`). In addition, only following siblings of the current node are included since page tree nodes are presented as flat node structure. This way, the current context is now actually taken into account.
=> [BUGFIX] Harden XPath query to limit search for page tree node

composer.json
This has been merged to dev-main (to be TF 9) already. TF 8 needs this change to keep core v13 compat.
TF needs this since core monorepo removed the copy of ClassMapGenerator with [1] for functional test
legacy instances of extensions.
> composer req composer/class-map-generator:^1.3.4
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/86184
=> [TASK] composer req composer/class-map-generator:^1.3.4 (#621)

Classes/Core/Functional/FunctionalTestCase.php
This change writes functioal test instance database
configuration using doctrine/dbal identifiers and
structure directly. Thus, avoiding the need for the
TYPO3 ConnectionPool to transform these values on
the fly.
Instead of default connection array
$GLOBALS['TYPO3_CONF_VARS_']['DB']['Connections']
['Default']['tableoptions'] = []
following array is written
$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']
['Default']['defaultTableOptions'] = []
for database driver `mysqli` and `pdo_mysql`, other
platforms does not suport these settings.
Additionally, `COLLATION` is used instead of the
replaced `COLLATE` subkey to define the table
collation within the default table options.
Backport to typo3/testing-framework v8 will limit
this to TYPO3 v13 and for v12 using the old values.
[1] …
=> [TASK] Mitigate deprecated database configuration

Classes/Core/SystemEnvironmentBuilder.php
TYPO3 core `SystemEnvironmentBuilder` has been implement
normal TYPO3 usages in mind respecting possible instance
setup scenarios, to build low level system environment
before taking configuration into account.
Path calculations are based on different indicators,
for example if TYPO3 is used in composer mode based
on the PHP define() TYPO3_COMPOSER_MODE set during
by the `typo3/cms-composer-installers` composer plugin
during `composer install` actions.
Per nature, PHP defines are immutable and cannot be
changed anymore during runtime.
As `typo3/testing-framework` is only installabe using
composer the TYPO3_COMPOSER_MODE define is always set
but is invalid for functional test instances build in
legacy mode and making invalid path calculations.
That was hidden quite some time now, and is …
=> [BUGFIX] Ensure correct path calculation on system build

Classes/Core/Testbase.php
=> [BUGFIX] Add missing parameter for `SystemEnvironmentBuilder::run()` call

Resources/Core/Functional/Extensions/json_response/Classes/Middleware/BackendUserHandler.php
Use TYPO3\CMS\Frontend\FrontendBackendUserAuthentication instead, the class has been moved from ext:backend to ext:frontend in TYPO3 v13, the old name has been established as alias and is removed with TYPO3 v14.
=> [BUGFIX] Avoid TYPO3\CMS\Backend\FrontendBackendUserAuthentication

Classes/Core/Testbase.php
`LocalConfiguration.php` has been replaces by `system/settings.php`, see https://forge.typo3.org/issues/98319. This adjusts corresponding test setup.
=> [BUGFIX] Use system.php for local configuration

.github/workflows/ci.yml
This reverts commit cd23e9f5fdad88ca3e99b49684f031498a320e8f,
which was a experimental try to mitigate an issue with scheduled
execution breaking external fork pull-requests. It's not needed
and removed again.
=> Revert "[TASK] Increase git fetch depth for pull-requests"

.github/workflows/ci.yml
With the introduction of non-main branch scheduled workflow
execution a adjusted checkout part in the `ci.yml` workflow
file has been added to allow to define which branch should
be checked out.
That breaks pipeline execution for pull-requests opened from
repository forks.
This change replaces the old detection with a more simplified
implementation, only setting the custom ref in case of github
workflow_dispatch event execution using `''` as fallback which
allows custom branch selection for workflow dispatching while
keeping default repostiory and branch checkout intact.
Releases: main, 8, 7
=> [TASK] Use simplier and working checkout ref determination

Build/phpstan/phpstan-baseline.neon, composer.json
> composer req --dev phpstan/phpstan:^2.0.2 phpstan/phpstan-phpunit:^2.0.1
> Build/Scripts/runTests.sh -s phpstanGenerateBaseline -p 8.2
=> [TASK] phpstan v2

Build/phpunit/UnitTests.xml, Classes/Core/Functional/FunctionalTestCase.php, Resources/Core/Build/FunctionalTests.xml, Resources/Core/Build/UnitTests.xml
When comparing with a csv fixture that contains a table with no rows, which is a legit case, no assertion is raised. This makes phpunit emit a risky test: "This test did not perform any assertions". The patch adds an assertion in this case as well.
Note phpunit nowadays has attribute #[DoesNotPerformAssertions] to mark tests that do not assert anything. This can be used for tests that for instance just call a subject method to verify no exception is raised. It is good to follow this path, the patch removes "beStrictAboutTestsThatDoNotTestAnything=false" from the example phpunit xml files, which makes this setting implicitly true.
Releases: main
Resolves: #647
=> [TASK] Trigger assertion in assertCSVDataSet() on empty table

Resources/Core/Functional/Extensions/json_response/composer.json, Resources/Core/Functional/Extensions/json_response/ext_emconf.php, Resources/Core/Functional/Extensions/private_container/composer.json, Resources/Core/Functional/Extensions/private_container/ext_emconf.php
The typo3/testing-framework provides two TYPO3 extensions,
which are required and bound to every created functional
test instance.
Adding missing `composer.json` for these two extensions.
=> [TASK] Add missing `composer.json` to testing-framework extensions

Build/phpstan/phpstan.neon, Classes/Composer/ComposerPackageManager.php, Classes/Core/PackageCollection.php, Tests/Unit/Composer/ComposerPackageManagerTest.php, Tests/Unit/Core/PackageCollectionTest.php, Tests/Unit/Fixtures/Packages/PackageStates.php, Tests/Unit/Fixtures/Packages/PackageStates_sorted.php, Tests/Unit/Fixtures/Packages/package-identifier/composer.json, Tests/Unit/Fixtures/Packages/package-unsynced-extemconf/composer.json, Tests/Unit/Fixtures/Packages/package-unsynced-extemconf/ext_emconf.php, Tests/Unit/Fixtures/Packages/package-with-extemconf/composer.json, Tests/Unit/Fixtures/Packages/package-with-extemconf/ext_emconf.php, Tests/Unit/Fixtures/Packages/package0/composer.json, Tests/Unit/Fixtures/Packages/package1/composer.json, Tests/Unit/Fixtures/Packages/package2-unsynced-extemconf/composer.json, Tests/Unit/Fixtures/Packages/package2-unsynced-extemconf/ext_emconf.php, Tests/Unit/Fixtures/Packages/package2/composer.json
The `typo3/testing-framework` creates functional test instances
as "classic" mode instances, writing a `PackageStates.php` file
composed using composer information, provided and handled by the
internal `ComposerPackageManager` class. Extensions in the state
file are not sorted based on their dependencies and suggestions.
To mitigate this and having a correctly sorted extension state
file, the `PackageCollection` service has been introduced with
the goal to resort the extension state file after the initial
write to provide the correct sorted extension state.
The extension sorting within the state file is important, as the
TYPO3 Core uses this sorting to loop over extensions to collect
information from the extensions, for example TCA, TCAOverrides,
ext_localconf.php and other things. …
=> [BUGFIX] Respect composer mode only extension in FunctionalTestCase

Classes/Core/Testbase.php
Using the `typo3DatabasePort` environment variable to
define the database server port string-casts the value
to an string which is not compatible with the mysqli
method `mysqli::real_connect()` and fails with:
```
TypeError: mysqli::real_connect(): Argument #5 ($port)
must be of type ?int, string given
```
This change casts the database port to an integer in case
a port is provided to avoid PHP TypeError when passing to
`mysqli::real_connect()` to align with `ConnectionPool`,
which is not used to create the database for the functional
test instance.
Resolves: #631
=> [BUGFIX] Avoid TypeError for database port handling

Classes/Core/Acceptance/Extension/BackendEnvironment.php
This change removes the enabling of feature `redirects.hitCount`
within codeception acceptance test setups to stay on TYPO3 Core
defaults.
That has been preared with temporary solution for TYPO3 Core tests [1].
* [1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/87280
Resolves: https://github.com/TYPO3/testing-framework/issues/554
Releases: main
=> [TASK] Do not enable feature `redirects.hitCount` for acceptance tests

Build/phpstan/phpstan.neon, Classes/Composer/ComposerPackageManager.php, Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Functional/FunctionalTestCase.php, Classes/Core/PackageCollection.php, Classes/Core/SystemEnvironmentBuilder.php, Classes/Core/Testbase.php, Resources/Core/Functional/Extensions/json_response/composer.json, Resources/Core/Functional/Extensions/json_response/ext_emconf.php, Resources/Core/Functional/Extensions/private_container/composer.json, Resources/Core/Functional/Extensions/private_container/ext_emconf.php, Tests/Unit/Composer/ComposerPackageManagerTest.php, Tests/Unit/Composer/Fixtures/Extensions/extension-key-shared-with-composer-package/composer.json, Tests/Unit/Composer/Fixtures/Packages/sharedextensionkey/composer.json, Tests/Unit/Core/PackageCollectionTest.php, Tests/Unit/Fixtures/Packages/PackageStates.php, Tests/Unit/Fixtures/Packages/PackageStates_sorted.php, Tests/Unit/Fixtures/Packages/package-identifier/composer.json, Tests/Unit/Fixtures/Packages/package-unsynced-extemconf/composer.json, Tests/Unit/Fixtures/Packages/package-unsynced-extemconf/ext_emconf.php, Tests/Unit/Fixtures/Packages/package-with-extemconf/composer.json, Tests/Unit/Fixtures/Packages/package-with-extemconf/ext_emconf.php, Tests/Unit/Fixtures/Packages/package0/composer.json, Tests/Unit/Fixtures/Packages/package1/composer.json, Tests/Unit/Fixtures/Packages/package2-unsynced-extemconf/composer.json, Tests/Unit/Fixtures/Packages/package2-unsynced-extemconf/ext_emconf.php, Tests/Unit/Fixtures/Packages/package2/composer.json
* against TYPO3 Core v12 with [87276: [WIP][TASK] test collected tf backport](https://review.typo3.org/c/Packages/TYPO3.CMS/+/87276)
:memo: [[TASK] Use non deprecated database connection options (tableoptions, collate)](https://github.com/TYPO3/testing-framework/pull/628)
* https://github.com/TYPO3/testing-framework/pull/640
:memo: [**[BUGFIX] Ensure correct path calculation on system build**](https://github.com/TYPO3/testing-framework/issues/577) 
Combined backport of:
* https://github.com/TYPO3/testing-framework/pull/630
* https://github.com/TYPO3/testing-framework/pull/632
:memo: [[TASK] Add missing composer.json to testing-framework extensions](https://github.com/TYPO3/testing-framework/pull/654)
* https://github.com/TYPO3/testing-framework/pull/654
:memo: [[BUGFIX] Respect composer …
=> [TASK] Collection of backports

Classes/Core/Testbase.php
The bugfix backport to ensure correct system environment path
building to fix issue #577 missed to correctly set the flag
for non-composer mode for TYPO3 v12 and lead to wrong path
calculations and followup issues within functional tests.
This is fixed by handing over a correct override value within
the functional test bootstrap.
[1] https://github.com/TYPO3/testing-framework/issues/577
[2] https://github.com/TYPO3/testing-framework/pull/633
Resolves: #658
Related: #633
Related: https://github.com/TYPO3/testing-framework/pull/633/commits/409c2b8e4551a9bdb40703e09c48ffcea2d74c42
Releases: 8
=> [BUGFIX] Ensure to take test instance as class mode instance

Classes/Core/Unit/UnitTestCase.php
phpunit has a best practice that tests should usually have at least one assertion to be sure they actually do something. All assertions thus raise a counter that is checked after test execution. If zero, phpunit marks the test risky with "test has no assertion".
There are two ways to suppress this:
* Setting beStrictAboutTestsThatDoNotTestAnything="false" via phpunit config
* Adding #[DoesNotPerformAssertions] attribute to single tests to actively mark tests that do not assert something as legit
Our abstract UnitTestCase spoils this by always doing assertions in tearDown(). The patch turns these
assertions into check+fail() code instead. Unit tests that don't have assertions for whatever reason are now properly marked as risky as intended by phpunit.
Releases: main
=> [TASK] Do not assertX but fail() in tearDown()

Classes/Core/Acceptance/Extension/BackendEnvironment.php, Classes/Core/Testbase.php
[TASK] Allow defining test instance files copy for acceptance tests
Running acceptance tests with codeception on a created
test instance with a real `Apache2` webserver requires
to have the `.htaccess` files in place, otherwise the
required rewriting to the endpoints will not work.
Since TYPO3 v13 with droppend backend entrypoint this
grows to a even higher requirement.
TYPO3 monorepo implemented that directly within the
extended `BackendEnvironment` class.
To make the live for developers easier using the
`typo3/testing-framework` for project or extension
acceptance testing a new tooling is now added based
on the direct monorepo implementation.
Following `BackendEnvironment::$config[]` options are
now available:
* `'copyInstanceFiles' => [],` (`array<string, string[]>`)
to copy the …
=> [TASK] Allow defining test instance files copy for acceptance tests

Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php
This change allows for YAML-based fixtures
to also add version variants for a language variant thus, making it fully overlayable.
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/72015
=> [BUGFIX] Allow to process versions of language variants

Classes/Core/Functional/Framework/DataHandling/ActionService.php
When a versioned record cannot be found, the
DB table and the UID of the live record is now
added to the message of the exception.
=> [TASK] Improve error message
