TYPO3/testing-framework

- Classes/Core/Acceptance/Support/Helper/ModalDialog.php
- Classes/Core/Testbase.php
- Resources/Core/Build/UnitTestsBootstrap.php
[FEATURE] Allow to override PATH_site via environment variables
[FEATURE] Improved JavaScript Modal API
> [TASK] Re-Add latest master changes

- Classes/Core/Functional/Framework/DataHandling/ActionService.php
Resolves: #19
Releases: master, 8.7
> [TASK] Add direct DataHandler invocation to ActionService

- Classes/Core/Functional/Framework/Frontend/Renderer.php
> [FEATURE] Add possibility to provide custom data in frontend-rendering

- Classes/Core/Functional/FunctionalTestCase.php
- Resources/Core/Functional/Fixtures/Frontend/request.tpl
> [TASK] Add request.tpl and adjust call in FunctionalTestCase.php

- Classes/Core/Functional/Framework/Frontend/Parser.php
Fixes: https://github.com/TYPO3/testing-framework/issues/29
> Fix fatal error in Parser::process

- Classes/Core/Acceptance/AcceptanceCoreEnvironment.php
- Classes/Core/Functional/FunctionalTestCase.php
- Classes/Core/Testbase.php
- Resources/Core/Build/UnitTestsBootstrap.php
With https://review.typo3.org/c/55773/ Bootstrap
is (mostly) stateless and uses static methods.
> [TASK] Use static Bootstrap methods

- Classes/Core/Acceptance/AcceptanceCoreEnvironment.php
The extension is needed for an existing Test
> [TASK] Add ext:sys_note to loaded sysexts during AccTest Bootstrap

- Resources/Core/Build/AcceptanceTests.yml
The issue has been resolved so the comment can be removed.
> [CLEANUP] Remove todo comment for resolved issue

- Classes/Core/Functional/FunctionalTestCase.php
- Classes/Core/Testbase.php
Running functionals with pdo_sqlite needs some minor set-up
adaptions since 'dbname' is not used, but 'path' instead,
and ->listDatabases() does not work and must not be triggered.
typo3DatabaseDriver=pdo_sqlite ./bin/phpunit \
-c vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml
> [TASK] Handle pdo_sqlite driver for sqlite3 core support

- Classes/Core/Functional/Framework/Frontend/Hook/BackendUserHandler.php
- Classes/Core/Functional/Framework/Frontend/Hook/FrontendUserHandler.php
- Classes/Core/Functional/Framework/Frontend/Hook/TypoScriptInstructionModifier.php
- Resources/Core/Functional/Extensions/json_response/Classes/Middleware/BackendUserHandler.php
- Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php
- Resources/Core/Functional/Extensions/json_response/Configuration/RequestMiddlewares.php
In order to get rid of the hooks, the EXT:json_response
should use PSR-15 middlewares instead.
> [TASK] Add middlewares to json_response

- Classes/Core/Functional/FunctionalTestCase.php
- Classes/Core/Unit/UnitTestCase.php
- Classes/Fluid/Unit/ViewHelpers/ViewHelperBaseTestcase.php
- composer.json
composer require phpunit/phpunit:^8
> [TASK] Update phpunit to version 8

- Resources/Core/Functional/Fixtures/sys_language.xml
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/60887/
> [TASK] Remove sys_language.static_lang_isocode

- Classes/Core/Testbase.php
- Resources/Core/Build/UnitTestsBootstrap.php
- composer.json
This reverts commit 0b4e0addc5c3bc501a9e9ffa98120d9599ba705c.
> Revert "[BUGFIX] Add compatibility to TYPO3 Core v9"

- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php
* be more strict for `version` entities
* fix page localization handling (localized pages had wrong pid)
> [BUGFIX] Streaming scenario creation

- Classes/Core/AccessibleObjectInterface.php
- Classes/Core/BaseTestCase.php
The other magic methods are not needed anymore.
> [!!!][TASK] Make AccessibleObject only work with call/get/set

- Classes/Core/AccessibleProxyTrait.php
- Classes/Core/BaseTestCase.php
Now its less code to be put into "eval()", which needs
to be removed eventually.
> [TASK] Use trait for AccessibleProxy

- composer.json
used command:
composer require mikey179/vfsstream:"~1.6.8"
> [TASK] Update mikey179/vfsstream to version 1.6.8

- Classes/Core/Acceptance/Helper/AbstractPageTree.php
> [BUGFIX] Use correct namespace for WebDriver (#172)

- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php
- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerWriter.php
> [TASK] Add support for basic actions in YAML scenarios

- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerWriter.php
This is a backport for https://github.com/TYPO3/testing-framework/pull/147 for v9 branch
> [BUGFIX] Consider negative new records in workspace datahandler tests

- Classes/Core/Acceptance/Helper/Acceptance.php
```
use TYPO3\TestingFramework\Core\Acceptance\Helper\Acceptance;
class SomeCest
{
public function someTest(Scenario $scenario)
{
$acceptance = $scenario->current('modules')['\\' . Acceptance::class] ?? null;
$acceptnance->allowBrowserError('/Found invalid token [[:digit:]]{40}/i');
...
```
> [TASK] Add possibility to define allowed browser console errors

- Resources/Core/Functional/Extensions/json_response/Configuration/RequestMiddlewares.php
> [BUGFIX] Use correct identifier for middleware registration

- Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php
The new method ->createUserAspect() is added
in TYPO3 v11, so the testing framework should
adapt the changes.
> [TASK] Enable setting of groups in middleware

- composer.json
> Do not fail on missing DB with Doctrine DBAL 2.13

- Classes/Core/Acceptance/Extension/BackendEnvironment.php
The test containers don't package imagemagick,
default configuration should be gm.
> [TASK] Configure acceptance tests to use graphics magick

- .github/pull_request_template.md
- CONTRIBUTING.rst
1. Add headings to GitHub pull request template
2. Adjust testing section in contribution guidelines:
- time for running TYPO3 Core functional and acceptance tests has been adjusted
- info that tests do not have to run successful but the same as before has been added
Nothing to test, this is only about documentation.
Changed documentation in GitHub UI.
> [TASK] Adjust GitHub template and contribution guidelines

- Classes/Core/Acceptance/Helper/Login.php
**Changes proposed in this pull request**:
The `$role` parameter of the `useExistingSession($role)` action was ignored
if another backend user was already logged in. In this example
```
$I->useExistingSession('admin');
$I->useExistingSession('editor');
```
the user "admin" was not changed to "editor" but the user "admin" remained
logged in.
With this patch, the action ensures that the requested user is logged in.
**Steps to test the solution**:
Insert these code lines into an arbitrary acceptance test of the TYPO3 Core:
```
..
$I->useExistingSession('editor');
$I->makeScreenshot('editor_backend');
$I->useExistingSession('admin');
$I->makeScreenshot('admin_backend');
``` 
and run the acceptance test by
```
./Build/Scripts/runTests.sh -s acceptance -e "[path to the core cest file]"
``` …
> [BUGFIX] Support switching of TYPO3 backend user in Login

- .gitattributes
This will reduce download size and improve download speed when this
package is used.
> [FEATURE] Keep development-only files out of the Composer packages

- Classes/Core/Functional/FunctionalTestCase.php
This change adds 
* clean backend user authentication for TYPO3 v11
* sets proper server parameters and normalizedParams
This way, the BE User object can receive a ServerRequest object for TYPO3 v11
see https://review.typo3.org/c/Packages/TYPO3.CMS/+/68797
> Change beuser

- Classes/Core/BaseTestCase.php
- Classes/Core/Exception.php
- Classes/Core/Functional/Framework/AssignablePropertyTrait.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/AbstractRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/AbstractStructureRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/DoesNotHaveRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/HasRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/StructureDoesNotHaveRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/StructureHasRecordConstraint.php
- Classes/Core/Functional/Framework/Frontend/Collector.php
- Classes/Core/Functional/Framework/Frontend/Hook/TypoScriptInstructionModifier.php
- Classes/Core/Functional/Framework/Frontend/Internal/AbstractInstruction.php
- Classes/Core/Functional/Framework/Frontend/Internal/ArrayValueInstruction.php
- Classes/Core/Functional/Framework/Frontend/Internal/TypoScriptInstruction.php
- Classes/Core/Functional/Framework/Frontend/InternalRequest.php
- Classes/Core/Functional/Framework/Frontend/Parser.php
- Classes/Core/Functional/Framework/Frontend/Renderer.php
- Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
- Classes/Core/Functional/Framework/Frontend/ResponseContent.php
- Classes/Core/Testbase.php
declare all classes as strict typed
> Strict types

- Build/Scripts/runTests.sh
- Build/testing-docker/docker-compose.yml
- composer.json
Various runTests.sh improvements plus the
casual CGL setup.
> [TASK] Have a proper CGL setup

- Build/phpstan/phpstan-baseline.neon
- Build/phpstan/phpstan-constants.php
- Build/phpstan/phpstan.neon
- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php
- Classes/Core/Functional/Framework/DataHandling/Scenario/EntityConfiguration.php
- Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php
- Classes/Core/Functional/Framework/FrameworkState.php
- Classes/Core/Testbase.php
Multip step phpstan level raise and minor fixes.
> [TASK] Multiple phpstan level raises along with minor changes

- composer.json
Also update PHPStan to the latest version.
> [TASK] Add PHPUnit rules for PHPStan

- Classes/Core/Functional/FunctionalTestCase.php
> [BUGFIX] Fix a typo in a variable name

- Build/phpstan/phpstan-baseline.neon
- Classes/Core/BaseTestCase.php
> [BUGFIX] Fix the type annotations for accessible proxies

- Tests/Unit/Core/Functional/Framework/DataHandling/DataSetTest.php
- composer.json
> [BUGFIX] Correct namespace of local Tests/ classes

- Classes/Core/Acceptance/Extension/BackendEnvironment.php
- Classes/Core/Acceptance/Helper/Login.php
* ensure proper property type hints
* ensure proper method return type
* follow renamed methods
This needs to be merged more or less timed with 
https://review.typo3.org/c/Packages/TYPO3.CMS/+/75317
> [TASK] Ensure codeception 5.0.x compatibility

- .github/workflows/ci.yml
- Build/Scripts/runTests.sh
- Build/testing-docker/docker-compose.yml
> [TASK] Add PHP 8.2 to test matrix

- README.md
> [TASK][#377] Add readme section for static data problem

- Resources/Core/Build/UnitTestsBootstrap.php
1. A code comment in `UnitTestsBootstrap.php` is fixed.
–
–
> [BUGFIX] Fix code comment in UnitTestsBootstrap.php

- Classes/Core/Functional/FunctionalTestCase.php
- composer.json
EXT:recordlist will be merged into EXT:backend
with core v12.
Releases: main
> [TASK] Remove dependency to cms-recordlist

- Build/phpstan/phpstan-baseline.neon
- Classes/Core/Functional/Framework/Frontend/Collector.php
The "Collector" - a helper construct for functional tests to render json output in frontend - can use
the new request attribute TypoScriptRequestAttribute to retrieve frontend TypoScript configuration.
> [TASK] Avoid using TSFE->tmpl in Collector

- composer.json
composer req --dev phpstan/phpstan:^1.9.2
> [TASK] Raise phpstan ^1.9.2

- Classes/Core/Functional/Framework/DataHandling/DataSet.php
With https://review.typo3.org/c/Packages/TYPO3.CMS/+/76553
support for native json database field has been introduced 
into TYPO3. This came along with automatic transformation 
from PHP-Value to database compatible values, which basicly 
means that the values get json-encode'd.
Providing fixture database values for JSON fields are now 
impossible to set, as string values get encoded as string
which does not write the expected values to the database.
This change uses the already used database schema information
and proper decode the values after reading from the csv files.
That ensures that the data written to the database has the
expected format. Othewise testing would be inpossible for
JSON-Fields.
> [TASK] Ensure fixture field data for json fields can be inserted

- Build/phpstan/phpstan-baseline.neon
- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php
- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerWriter.php
- Classes/Core/Functional/Framework/DataHandling/Scenario/EntityConfiguration.php
- Classes/Core/Functional/Framework/Frontend/ResponseContent.php
See [1]. I hesitant declaring the entire classes
final at the moment, but final __construct()
should be fine for now.
[1] https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static
> [TASK] Avoid phpstan "Unsafe usage of new static()"

- Build/phpstan/phpstan-baseline.neon
- Classes/Core/BaseTestCase.php
This pull-request contains to commits to solve
minor version crossing issues with phpunit pre
and post 10.1.
See commit messages for detailed information.
> [TASK] Ensure phpunit 10.1 and older combat

- Build/phpstan/phpstan-baseline.neon
- Classes/Core/Functional/FunctionalTestCase.php
This pull-request contains to commits to solve
minor version crossing issues with phpunit pre
and post 10.1.
See commit messages for detailed information.
Backport for PR #452
> [BACKPORT][TASK] Ensure phpunit 10.1 and older combat

- Build/Scripts/runTests.sh
- Build/testing-docker/docker-compose.yml
- Classes/Core/Testbase.php
Pull-request for backport changes.
> [TASK] Backport of merged main changes

- Resources/Core/Build/FunctionalTests.xml
- Resources/Core/Build/UnitTests.xml
> [TASK] phpunit configuration for v10.1

- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php
php-cs-fixer seems to have changed something or
fixed a bug. However, this leads to a change in
detections.
This changes simply applies the rules fixes to
be aligned with choosen rules.
Used command(s):
```shell
Build/Scripts/runTests.sh -s cgl
```
> [TASK] Apply cgl fix

- Classes/Core/Acceptance/Extension/BackendEnvironment.php
- Classes/Core/Functional/FunctionalTestCase.php
- Classes/Core/Testbase.php
Core SchemaMigrator is being prepared towards
DI. TF now needs to get an instance of that
service from container to unblock core patches.
Releases: main
> [TASK] Get SchemaMigrator instance from container

- Build/phpstan/phpstan-baseline.neon
- Classes/Core/BaseTestCase.php
TF main requires phpunit ^10.1, we can
ditch a hack needod only for lower versions.
Releases: main
> [TASK] Remove phpunit < 10.1 compat hack

- Classes/Core/Functional/FunctionalTestCase.php
To phase out <INCLUDE_TYPOSCRIPT in core, testing-framework needs to switch to @import as well.
FunctionalTestCase->setUpFrontendRootPage() now accepts only typoscript files referenced using "EXT:" syntax and deprecates the old way.
> [TASK] Avoid INCLUDE_TYPOSCRIPT to load typoscript files

- Classes/Core/Functional/FunctionalTestCase.php
> [TASK] Avoid invalid database name configuration 

- Classes/Core/Testbase.php
The doctrine team deprecated the instantiation of a connection
using `DriverManager::getConnection()` without a configuration
object [1].
This change ensures to set the default doctrine factory, but
sets the TYPO3 core implementation with TYPO3 v13.0 to provide
the custom SchemaManager for the different platforms.
[1] https://github.com/doctrine/dbal/blob/3.7.x/UPGRADE.md#deprecated-not-setting-a-schema-manager-factory
Releases: main
> [TASK] Ensure to set a SchemaManagerFactory for lowlevel connection

- Classes/Core/BaseTestCase.php
PHPUnit changed the error handler behaviour and introduced the PHP
attribute `#[WithoutErrorHandler]` to omit the error handler for
test methods.
This breaks the dangling error handler check provided by the
`typo3/testing-framework` which assumes that the PHPUnit error
handler is always the only registered error handler.
This change modifies the `BaseTestCase` class
* to provide the borrowed `shouldErrorHandlerBeUsed()` method
cloned from `TestRunner` with additional version guards.
* to align the dangling error handler check in the `tearDown()`
method of the `BaseTestCase` class using the added method.
Related: https://forge.typo3.org/issues/102724
> [TASK] Respect `#[WithoutErrorHandler]` for error handler integrity check

- Classes/Core/Functional/Framework/DataHandling/Snapshot/DatabaseAccessor.php
Doctrine DBAL 4 transform the `ParameterType`
from class to a native enum, which is a non
baked enum which prevents serialization of
the enum, for example using `json_encode()`.
The `DatabaseAccessor` used for the function
test `withSnapshot()` feature encodes column
information of the snapshotted data as json,
badly breaking down with `Doctrine DBAL 4`.
`TYPO3\CMS\Core\Database\Connection` has been
modified to determine the parameter types for
`insert()`, `update()` and similar methods
based on the database structure if the types
are not passed.
This change modifes the column preparation
to avoid the enum type and instead save the
doctrine type name as string. This is only
done, if `ParameterType` is a real enum and
therefore only with `Doctrine DBAL 4`.
The adjustment on the …
> [TASK] Avoid json encoding of `ParameterType`

- .github/workflows/ci.yml
> [TASK] GH workflows actions/checkout@v4

- Classes/Core/Functional/FunctionalTestCase.php
v13 aims to remove that internal method.
Resolves: #556
> [TASK] Call TSFE->releaseLocks() only if method exists

- Classes/Core/BaseTestCase.php
Remove two obsolete exceptions - empty string will throw in \ReflectionClass by PHP.
> [TASK] Happify phpstan

- composer.json
> [TASK] composer req psr/container:^2.0

- composer.json
Similar to core v13: Drop phpunit v10
> [TASK] composer req phpunit/phpunit:^11.2.5

- composer.json
> composer req --dev phpstan/phpstan:^1.11.5
> composer req --dev phpstan/phpstan-phpunit:^1.4.0
> [TASK] Bump phpstan & friends

- Classes/Core/PackageCollection.php
- Classes/Core/SystemEnvironmentBuilder.php
Removes a b/w compat layer for TYPO3 v12.
> [TASK] Set SystemEnvironmentBuilder->run $requestType to 0

- Classes/Core/Functional/FunctionalTestCase.php
Remove various TYPO3 v12 b/w compat code
from FunctionalTestCase.
> [TASK] Clean up FunctionalTestCase

- Classes/Core/Functional/Framework/Constraint/RequestSection/AbstractRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/AbstractStructureRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/DoesNotHaveRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/HasRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/StructureDoesNotHaveRecordConstraint.php
- Classes/Core/Functional/Framework/Constraint/RequestSection/StructureHasRecordConstraint.php
- Classes/Core/Functional/Framework/FrameworkState.php
Improved type and return value hinting.
> [TASK] Harden Core\Functional\Framework\Constraint\RequestSection

- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerFactory.php
- Classes/Core/Functional/Framework/DataHandling/Scenario/DataHandlerWriter.php
- Classes/Core/Functional/Framework/DataHandling/Scenario/EntityConfiguration.php
Improved type and return value hinting.
> [TASK] Harden Core\Functional\Framework\DataHandling\Scenario

- Classes/Core/Functional/Framework/Frontend/Internal/ArrayValueInstruction.php
- Classes/Core/Functional/Framework/Frontend/Internal/InstructionInterface.php
- Classes/Core/Functional/Framework/Frontend/Internal/TypoScriptInstruction.php
- Classes/Core/Functional/Framework/Frontend/InternalRequest.php
Have an interface to avoid type hinting
AbstractInstruction.
> [TASK] Add InstructionInterface

- Classes/Core/Testbase.php
The `Testbase->setUpTestDatabase()` takes care of
correct database setup for each test instance and
that the database is created. To accomplish that,
current TYPO3 connections are closed.
Doctrine DriverManager is used as lowlevel tool
to create the instance database.
In case that the database has not been created,
which occures on the first test execution per
test-case, an exception is thrown and disturbes
the `getDatabasePlatform <-> getServerVersion()`
detection with the Doctrine construct. That has
been mitigated by catching the exception within
`Connection->getServerVersion()` and returning
an empty string ending up retrieving at least a
the lowest default platform for the driver. That
was mainly a workaround in functional test runs.
Doctrine DBAL 3.9.x & 4.1.x will introduce a new …
> [TASK] Streamline `Testbase->setUpTestDatabase()`

- Classes/Core/BaseTestCase.php
> [FEATURE] getAccessibleMock() supports readonly classes

- Classes/Core/Functional/FunctionalTestCase.php
This change writes functioal test instance database
configuration using doctrine/dbal identifiers and
structure directly. Thus, avoiding the need for the
TYPO3 ConnectionPool to transform these values on
the fly.
Instead of default connection array
$GLOBALS['TYPO3_CONF_VARS_']['DB']['Connections']
['Default']['tableoptions'] = []
following array is written
$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']
['Default']['defaultTableOptions'] = []
for database driver `mysqli` and `pdo_mysql`, other
platforms does not suport these settings.
Additionally, `COLLATION` is used instead of the
replaced `COLLATE` subkey to define the table
collation within the default table options.
Backport to typo3/testing-framework v8 will limit
this to TYPO3 v13 and for v12 using the old values.
[1] …
> [TASK] Mitigate deprecated database configuration

- Resources/Core/Build/FunctionalTestsBootstrap.php
- Resources/Core/Build/UnitTestsBootstrap.php
- Resources/Core/Functional/Extensions/json_response/Configuration/RequestMiddlewares.php
- composer.json
> composer req --dev friendsofphp/php-cs-fixer:^3.65.0
Releases: main, 8, 7
> [TASK] Use friendsofphp/php-cs-fixer:^3.65.0 and fix cgl

- Build/phpstan/phpstan-baseline.neon
- composer.json
> composer req --dev phpstan/phpstan:^2.0.2 phpstan/phpstan-phpunit:^2.0.1
> Build/Scripts/runTests.sh -s phpstanGenerateBaseline -p 8.2
> [TASK] phpstan v2

- Classes/Core/Testbase.php
`typo3/testing-framework` provides a extended `SystemEnvironmentBuilder`
to ensure correct instance initialization as classic mode in different
test context environment, allowing to manual set the composer mode flag
despite having the PHP define from parent composer installation as source.
`Testbase->setUpInstanceCoreLinks()` additionally provides TYPO3 entrypoints
in form of index.php files, calling the basic bootstrap, based on template
files from system extensions and modified to use the `typo3/testing-framework`
`SystemEnvironmentBuilder` but does not enforce non-composer (classic) mode.
This does not hurt within functional tests but codeception based accceptance
instances misses the enforced classic mode which can lead to several issues,
for example normalizedParams path calculation …
> [BUGFIX] Enforce classic mode in created TYPO3 entrypoint files
